import { country, type CountrySeed } from "../define";

const ADVICE = "Check your government's travel advice before going.";
const NO_TRAVEL = "Most governments advise against all travel.";

export const africa: CountrySeed[] = [
  country("EG", "The Pyramids, the Nile, pharaonic temples and Red Sea diving.", "Exporting any antiquity is a crime, and 'papyrus' sold cheaply in the street is usually banana leaf.", [
    ["papyrus", "art", "budget", "all", "art history", "Painted papyrus", "Buy from a papyrus workshop that shows how the sheets are made."],
    ["cartouche", "jewelry", "mid", "teens+", "jewelry history", "Cartouche pendant", "Your name in hieroglyphs, made to order in a day."],
    ["cotton", "decor", "mid", "adults", "home-decor fashion", "Egyptian cotton", "Long-staple cotton sheets, towels and shirts."],
    ["alabaster", "decor", "mid", "adults", "home-decor crafts", "Alabaster vase", "Carved in workshops on the west bank at Luxor."],
    ["perfume-bottle", "decor", "budget", "adults", "home-decor beauty crafts", "Glass perfume bottle", "Delicate hand-blown bottles; pack them carefully."],
    ["karkade", "food", "budget", "adults", "cooking drinks", "Karkade and spices", "Dried hibiscus for tea, with cumin and dukkah from the spice market."],
    ["scarab", "decor", "budget", "kids", "history collectibles", "Scarab amulet", "A stone beetle, the ancient symbol of rebirth."],
  ]),
  country("MA", "Medinas, souks, the Sahara, tagine and mint tea.", "Bargaining is expected in the souks, and the dirham may not be taken out of the country.", [
    ["argan-oil", "cosmetics", "mid", "adults", "beauty", "Argan oil", "Pressed by women's cooperatives in the south-west."],
    ["babouches", "clothing", "budget", "all", "fashion crafts tradition", "Babouches", "Soft leather slippers in every colour."],
    ["tagine", "decor", "mid", "adults", "cooking home-decor", "Tagine pot", "Choose an unglazed one for cooking, a painted one for serving."],
    ["berber-carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Berber carpet", "Hand-knotted wool rugs from the Atlas."],
    ["tea-set", "decor", "mid", "adults", "drinks home-decor tradition", "Mint-tea set", "A silver-coloured teapot and painted glasses."],
    ["ras-el-hanout", "food", "budget", "adults", "cooking", "Ras el hanout", "The spice merchant's own blend of dozens of spices."],
    ["lantern", "decor", "mid", "adults", "home-decor crafts", "Pierced metal lantern", "Throws patterned light across the room."],
    ["leather-bag", "accessory", "mid", "adults", "fashion crafts", "Leather bag", "From the tanneries of Fez."],
  ]),
  country("ZA", "Safaris, Table Mountain, wine and the legacy of Nelson Mandela.", "Ivory and rhino horn are illegal, and wood or hide items may need declaring at your home border.", [
    ["rooibos", "drink", "budget", "all", "drinks", "Rooibos tea", "Caffeine-free red tea that grows only in the Cederberg.", { soft: true }],
    ["biltong", "food", "budget", "adults", "food", "Biltong", "Air-dried spiced meat; check meat import rules at home."],
    ["pinotage", "drink", "mid", "adults", "drinks", "Pinotage", "South Africa's own red grape, from the Cape winelands."],
    ["beadwork", "jewelry", "budget", "all", "jewelry crafts tradition", "Zulu beadwork", "Colours and patterns once carried messages."],
    ["cream-liqueur", "drink", "mid", "adults", "drinks", "Marula cream liqueur", "Made from the fruit elephants are said to love."],
    ["shweshwe", "clothing", "mid", "adults", "fashion crafts", "Shweshwe fabric", "Printed indigo cotton with tiny geometric patterns."],
    ["wire-art", "craft", "budget", "all", "crafts art humor", "Wire-and-bead animal", "Township craft made from wire and glass beads."],
  ]),
  country("KE", "The Maasai Mara, the wildebeest migration and long-distance runners.", "Plastic bags are banned, and ivory and other wildlife products are illegal.", [
    ["kikoy", "clothing", "budget", "all", "fashion", "Kikoy", "A striped cotton wrap from the coast."],
    ["maasai-beads", "jewelry", "budget", "all", "jewelry crafts tradition", "Maasai beadwork", "Collars and bracelets in bold colours."],
    ["coffee", "drink", "budget", "adults", "drinks", "Kenyan coffee", "Bright, fruity AA-grade beans.", { soft: true }],
    ["tea", "drink", "budget", "adults", "drinks", "Kenyan tea", "Strong black tea from the highlands around Kericho.", { soft: true }],
    ["soapstone", "decor", "budget", "all", "art crafts home-decor", "Kisii soapstone", "Carved and dyed stone animals and bowls."],
    ["kiondo", "accessory", "mid", "adults", "fashion crafts", "Kiondo", "A handwoven sisal basket bag."],
  ]),
  country("TZ", "The Serengeti, Kilimanjaro and Zanzibar.", "Plastic bags are banned, and tanzanite should be bought only with a certificate.", [
    ["tanzanite", "jewelry", "premium", "adults", "jewelry", "Tanzanite", "A blue-violet gem found only near Kilimanjaro."],
    ["tingatinga", "art", "mid", "all", "art humor", "Tingatinga painting", "Bright enamel paintings of animals."],
    ["spices", "food", "budget", "adults", "cooking", "Zanzibar spices", "Cloves, vanilla and cinnamon from the spice island."],
    ["coffee", "drink", "budget", "adults", "drinks", "Kilimanjaro coffee", "Arabica grown on the mountain's slopes.", { soft: true }],
    ["kanga", "clothing", "budget", "adults", "fashion tradition", "Kanga", "A printed cloth carrying a Swahili proverb."],
  ]),
  country("TN", "Roman Carthage, Mediterranean beaches, the Sahara and blue-and-white Sidi Bou Said.", "The dinar cannot be taken out of the country; change it back before leaving.", [
    ["olive-oil", "food", "mid", "adults", "cooking", "Olive oil", "Tunisia is one of the world's largest producers."],
    ["nabeul-ceramics", "decor", "mid", "adults", "home-decor crafts", "Nabeul ceramics", "Hand-painted plates and bowls."],
    ["chechia", "clothing", "budget", "adults", "tradition fashion", "Chechia", "The red felt cap."],
    ["harissa", "food", "budget", "adults", "cooking food", "Harissa", "Chilli paste, the national condiment."],
    ["birdcage", "decor", "mid", "adults", "home-decor crafts", "Sidi Bou Said birdcage", "A white-and-blue wire cage shaped like a domed house."],
    ["dates", "food", "budget", "all", "sweets", "Deglet Nour dates", "Translucent 'dates of light' sold on the branch."],
  ]),
  country("ET", "The birthplace of coffee, rock-hewn churches, and its own calendar and alphabet.", "Old crosses, manuscripts and other antiques cannot be exported without a museum permit.", [
    ["coffee", "drink", "budget", "adults", "drinks tradition", "Ethiopian coffee", "Beans from Yirgacheffe, Sidamo or Harar.", { soft: true }],
    ["jebena", "decor", "budget", "adults", "drinks tradition crafts", "Jebena", "The clay pot used in the coffee ceremony."],
    ["netela", "clothing", "mid", "adults", "fashion crafts tradition", "Netela", "A light handwoven cotton shawl with a coloured border."],
    ["cross", "jewelry", "mid", "adults", "jewelry tradition", "Ethiopian cross", "Each region has its own design; buy new ones."],
    ["berbere", "food", "budget", "adults", "cooking", "Berbere", "The fiery spice blend behind Ethiopian stews."],
    ["basket", "decor", "mid", "adults", "crafts home-decor", "Woven basket", "Tightly coiled and brightly coloured, especially from Harar."],
  ]),
  country("GH", "Kente cloth, gold, cocoa and the coastal slave-trade forts.", "Bargaining is normal in markets; fabric is sold in six- or twelve-yard lengths.", [
    ["kente", "clothing", "premium", "adults", "fashion crafts tradition", "Kente", "Strip-woven cloth of the Ashanti and Ewe."],
    ["shea-butter", "cosmetics", "budget", "adults", "beauty", "Shea butter", "Unrefined, from women's cooperatives in the north."],
    ["chocolate", "food", "budget", "all", "sweets", "Ghanaian chocolate", "From one of the world's largest cocoa growers."],
    ["adinkra", "decor", "mid", "adults", "crafts tradition art", "Adinkra cloth", "Stamped with symbols that each carry a proverb."],
    ["krobo-beads", "jewelry", "budget", "all", "jewelry crafts", "Krobo beads", "Made from recycled glass."],
  ]),
  country("NG", "Nollywood, Afrobeats, vast markets and Africa's largest population.", "Antiques and old artworks need clearance from the national museum authority to leave the country.", [
    ["ankara", "clothing", "mid", "adults", "fashion crafts", "Ankara fabric", "Bold wax prints, often tailored within a day."],
    ["adire", "clothing", "mid", "adults", "fashion crafts tradition", "Adire", "Yoruba indigo resist-dyed cloth."],
    ["music-merch", "music", "budget", "teens+", "music", "Afrobeats album or shirt", "Music by the artists who took Nigerian pop worldwide."],
    ["talking-drum", "music", "mid", "adults", "music tradition", "Talking drum", "An hourglass drum whose pitch imitates speech."],
    ["beads", "jewelry", "budget", "adults", "jewelry tradition", "Beaded jewellery", "Strands in the style of royal coral beads."],
    ["bronze", "art", "premium", "adults", "art history", "Bronze casting", "New lost-wax casts from the guild in Benin City."],
  ]),
  country("SN", "Dakar's music scene, Gorée Island, wrestling and teranga hospitality.", "Bargaining is expected; carry glass paintings flat between sheets of cardboard.", [
    ["sous-verre", "art", "mid", "adults", "art tradition", "Sous-verre painting", "Scenes painted in reverse on glass."],
    ["wax-fabric", "clothing", "mid", "adults", "fashion crafts", "Wax-print fabric", "Tailors in the markets sew it to measure."],
    ["basket", "decor", "mid", "adults", "home-decor crafts", "Wolof basket", "Coiled grass bound with coloured plastic strips."],
    ["bissap", "food", "budget", "adults", "drinks cooking", "Bissap", "Dried hibiscus flowers for the national drink."],
    ["djembe", "music", "mid", "teens+", "music tradition", "Djembe", "A goatskin hand drum."],
  ]),
  country("MU", "Lagoons, sugar cane, the extinct dodo and a blend of cultures.", "Shells and corals may not be exported without a permit.", [
    ["rum", "drink", "mid", "adults", "drinks", "Mauritian rum", "Agricultural rum, often infused with vanilla or fruit."],
    ["ship-model", "decor", "premium", "adults", "home-decor crafts collectibles history", "Model sailing ship", "Detailed wooden replicas, a local speciality."],
    ["sugar", "food", "budget", "all", "sweets cooking", "Speciality sugars", "A dozen unrefined cane sugars, from golden to molasses."],
    ["vanilla-tea", "drink", "budget", "adults", "drinks", "Vanilla tea", "Black tea from the island's own estate.", { soft: true }],
    ["dodo", "toy", "budget", "child", "toys nature humor", "Plush dodo", "The flightless bird that lived only here."],
  ]),
  country("SC", "Granite-boulder beaches, giant tortoises and the coco de mer palm.", "A coco de mer nut may be exported only with an official permit and numbered tag from a licensed seller.", [
    ["coco-de-mer", "decor", "premium", "adults", "nature collectibles", "Coco de mer", "The world's largest seed, sold polished with its export permit."],
    ["vanilla", "food", "budget", "adults", "cooking", "Vanilla and cinnamon", "Grown in old plantation gardens."],
    ["rum", "drink", "mid", "adults", "drinks", "Seychelles rum", "Distilled on Mahé."],
    ["tea", "drink", "budget", "adults", "drinks", "Seychelles tea", "From the hillside tea factory on Mahé.", { soft: true }],
  ]),
  country("NA", "The Namib dunes, Etosha's wildlife and vast empty landscapes.", "Distances are long and many roads are gravel; refuel whenever you can.", [
    ["eggshell-beads", "jewelry", "budget", "adults", "jewelry crafts tradition", "Ostrich-eggshell beads", "Made by San craftspeople."],
    ["basket", "decor", "mid", "adults", "crafts", "Kavango basket", "Woven from makalani palm."],
    ["tourmaline", "jewelry", "mid", "adults", "jewelry nature", "Namibian tourmaline", "Semi-precious stones from local mines."],
    ["nara-oil", "cosmetics", "mid", "adults", "beauty", "!Nara oil", "From a desert melon harvested by the Topnaar people."],
    ["herero-doll", "toy", "mid", "kids", "toys tradition crafts", "Herero doll", "Dressed in the full Victorian-style gown."],
  ]),
  country("MG", "Lemurs, baobabs and wildlife found nowhere else.", "Rosewood, tortoise shell and many plants and animals cannot be exported, and vanilla is limited per person.", [
    ["vanilla", "food", "mid", "adults", "cooking food", "Vanilla", "Madagascar grows most of the world's supply."],
    ["raffia-bag", "accessory", "budget", "adults", "fashion crafts", "Raffia bag", "Woven from palm fibre."],
    ["antemoro-paper", "craft", "budget", "all", "crafts art", "Antemoro paper", "Handmade paper with pressed flowers."],
    ["chocolate", "food", "mid", "all", "sweets", "Single-origin chocolate", "Made on the island from local cocoa."],
    ["lamba", "clothing", "mid", "adults", "fashion tradition", "Lamba", "The traditional wrap, in cotton or wild silk."],
  ]),
  country("DZ", "The Sahara, Roman ruins and the Casbah of Algiers.", "The dinar cannot be exported; keep your exchange receipts.", [
    ["dates", "food", "budget", "all", "sweets", "Deglet Nour dates", "From the oases of Biskra."],
    ["carpet", "decor", "premium", "adults", "home-decor crafts", "Ghardaïa carpet", "Geometric wool rugs from the M'zab valley."],
    ["tuareg-silver", "jewelry", "mid", "adults", "jewelry crafts tradition", "Tuareg silver", "Engraved crosses and pendants."],
    ["pottery", "decor", "mid", "adults", "home-decor crafts", "Kabyle pottery", "Earthenware painted with Berber symbols."],
  ]),
  country("AO", "Atlantic coastline, the Kalandula Falls and kizomba music.", "Portuguese is the working language; little English is spoken outside Luanda.", [
    ["pensador", "decor", "mid", "adults", "art tradition", "O Pensador", "The seated 'thinker' figure, a national symbol."],
    ["samakaka", "clothing", "mid", "adults", "fashion tradition", "Samakaka fabric", "A red, black and yellow geometric print."],
    ["coffee", "drink", "budget", "adults", "drinks", "Angolan coffee", "Robusta from a once-famous growing country.", { soft: true }],
    ["kizomba", "music", "budget", "adults", "music", "Kizomba recording", "The dance music Angola gave the world."],
  ]),
  country("BJ", "The birthplace of Vodun, the royal palaces of Abomey and villages on stilts.", "The national Vodun festival takes place on 10 January.", [
    ["applique", "art", "mid", "adults", "art tradition crafts", "Abomey appliqué", "Cloth hangings showing the emblems of the kings."],
    ["bronze", "art", "mid", "adults", "art crafts", "Bronze figure", "Small lost-wax castings."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "From the great market of Cotonou."],
    ["peanut-snack", "food", "budget", "all", "food", "Kluiklui", "Crunchy fried peanut sticks."],
  ]),
  country("BW", "The Okavango Delta, elephants and diamonds.", "Game products need export permits; buy diamonds only with a certificate.", [
    ["basket", "decor", "mid", "adults", "home-decor crafts tradition", "Botswana basket", "Finely coiled palm baskets from the delta."],
    ["eggshell-jewelry", "jewelry", "budget", "adults", "jewelry crafts tradition", "Eggshell jewellery", "Ostrich-eggshell beads made by San communities."],
    ["diamond", "jewelry", "premium", "adults", "jewelry", "Diamond", "From the world's leading producer by value."],
    ["marula-oil", "cosmetics", "budget", "adults", "beauty", "Marula oil", "A light skin oil from marula kernels."],
  ]),
  country("BF", "Mask festivals, the FESPACO film festival and bronze casters.", ADVICE, [
    ["bronze", "art", "mid", "adults", "art crafts", "Bronze figure", "From the casters' quarter in Ouagadougou."],
    ["faso-dan-fani", "clothing", "mid", "adults", "fashion tradition crafts", "Faso dan fani", "Handwoven striped cotton, the national cloth."],
    ["shea-butter", "cosmetics", "budget", "adults", "beauty", "Shea butter", "A major local product, made by women's groups."],
    ["mask", "decor", "mid", "adults", "art tradition", "Carved mask", "Newly carved in the styles of the Bwa and Mossi."],
  ]),
  country("BI", "Royal drummers, Lake Tanganyika and hillside tea and coffee.", ADVICE, [
    ["coffee", "drink", "budget", "adults", "drinks", "Burundi coffee", "Bourbon arabica from smallholder farms.", { soft: true }],
    ["drum", "music", "mid", "adults", "music tradition", "Miniature drum", "A small version of the royal drums."],
    ["basket", "decor", "budget", "adults", "crafts", "Woven basket", "Lidded baskets with conical tops."],
    ["tea", "drink", "budget", "adults", "drinks", "Burundi tea", "Grown at high altitude.", { soft: true }],
  ]),
  country("CV", "Morna music, volcanic islands and year-round sunshine.", "Products made from sea-turtle shell are illegal.", [
    ["grogue", "drink", "mid", "adults", "drinks", "Grogue", "Sugar-cane spirit from Santo Antão."],
    ["morna", "music", "budget", "adults", "music", "Morna recording", "The wistful music made famous by Cesária Évora."],
    ["coffee", "drink", "mid", "adults", "drinks", "Fogo coffee", "Grown on the slopes of the volcano.", { soft: true }],
    ["pano", "clothing", "mid", "adults", "tradition crafts", "Pano di terra", "Narrow-strip woven cloth in indigo and white."],
  ]),
  country("CM", "'Africa in miniature': rainforest, savanna, volcanoes and football.", ADVICE, [
    ["coffee", "drink", "budget", "adults", "drinks", "Cameroonian coffee", "From the western highlands.", { soft: true }],
    ["toghu", "clothing", "mid", "adults", "fashion tradition", "Toghu", "Black cloth with bright embroidery from the north-west."],
    ["football-shirt", "clothing", "mid", "all", "sports", "Indomitable Lions shirt", "The national team's green jersey."],
    ["beadwork", "craft", "mid", "adults", "art crafts tradition", "Bamileke beadwork", "Beaded figures and stools."],
  ]),
  country("CF", "Rainforest, forest elephants and river landscapes.", NO_TRAVEL, [
    ["coffee", "drink", "budget", "adults", "drinks", "Local coffee", "Robusta from the forest zone.", { soft: true }],
    ["basket", "craft", "budget", "adults", "crafts", "Woven basket", "Made from forest vines and palm."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "Sold by the length in Bangui's market."],
    ["carving", "decor", "mid", "adults", "art crafts", "Wood carving", "Newly carved figures and stools."],
  ]),
  country("TD", "The Sahara, Lake Chad and the rock arches of the Ennedi.", "Most governments advise against travel, and photography requires a permit.", [
    ["leather", "accessory", "mid", "adults", "crafts", "Leatherwork", "Bags and cushions with coloured appliqué."],
    ["dihe", "food", "budget", "adults", "food nature", "Dihé", "Dried spirulina harvested from Lake Chad."],
    ["silver", "jewelry", "mid", "adults", "jewelry tradition", "Saharan silver", "Engraved jewellery of the desert peoples."],
    ["mat", "decor", "budget", "adults", "crafts home-decor", "Woven mat", "Dyed palm-leaf mats."],
  ]),
  country("KM", "Ylang-ylang plantations, an active volcano and the coelacanth.", "The islands supply much of the world's ylang-ylang oil for perfume.", [
    ["ylang-ylang", "cosmetics", "mid", "adults", "beauty", "Ylang-ylang oil", "Essential oil distilled on the islands."],
    ["vanilla", "food", "budget", "adults", "cooking", "Vanilla", "Bourbon vanilla pods."],
    ["cloves", "food", "budget", "adults", "cooking", "Cloves", "A main export crop."],
    ["kofia", "clothing", "budget", "adults", "tradition fashion", "Kofia", "A hand-embroidered cap."],
  ]),
  country("CG", "The Congo River, gorillas and the sharply dressed sapeurs.", "Photographing government buildings is prohibited.", [
    ["painting", "art", "mid", "adults", "art", "Poto-Poto painting", "From Brazzaville's well-known painting school."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "The raw material of Congolese elegance."],
    ["raffia-cloth", "decor", "mid", "adults", "crafts tradition", "Raffia cloth", "Woven palm-fibre panels."],
    ["basket", "craft", "budget", "adults", "crafts", "Woven basket", "From the river markets."],
  ]),
  country("CD", "The Congo rainforest, mountain gorillas and rumba.", "Ivory is illegal; check your government's travel advice for the east of the country.", [
    ["malachite", "jewelry", "mid", "adults", "jewelry nature", "Malachite", "Banded green stone from the copper belt."],
    ["kuba-cloth", "decor", "mid", "adults", "art crafts tradition", "Kuba cloth", "Raffia panels with cut-pile geometric designs."],
    ["rumba", "music", "budget", "adults", "music", "Congolese rumba recording", "The sound that shaped African pop music."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "Sold in six-yard pieces."],
  ]),
  country("CI", "Cocoa, masks, the basilica of Yamoussoukro and coupé-décalé music.", "Bargaining is expected in craft markets.", [
    ["chocolate", "food", "budget", "all", "sweets", "Ivorian chocolate", "From the world's largest cocoa producer."],
    ["korhogo-cloth", "art", "mid", "adults", "art crafts tradition", "Korhogo cloth", "Cotton painted with figures in mud dye."],
    ["mask", "decor", "mid", "adults", "art tradition", "Carved mask", "New carvings in Baule and Dan styles."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "From the markets of Abidjan."],
  ]),
  country("DJ", "Salt lakes, volcanic deserts and whale sharks.", "Photographing ports, bridges and military sites is prohibited.", [
    ["salt", "food", "budget", "adults", "cooking nature", "Lake Assal salt", "Salt pearls from the lowest point in Africa."],
    ["mat", "decor", "budget", "adults", "crafts home-decor", "Afar mat", "Woven palm-leaf mats."],
    ["frankincense", "cosmetics", "budget", "adults", "beauty", "Frankincense", "Resin burned in every home."],
    ["futa", "clothing", "budget", "adults", "fashion tradition", "Futa", "A cotton wrap worn by men."],
  ]),
  country("GQ", "Rainforest islands and Spanish as an official language.", "Ask before photographing buildings; a permit may be required.", [
    ["chocolate", "food", "mid", "all", "sweets", "Bioko cocoa", "Chocolate from the island's old plantations."],
    ["carving", "decor", "mid", "adults", "art crafts", "Wood carving", "New figures in the Fang style."],
    ["fabric", "clothing", "budget", "adults", "fashion", "Printed fabric", "Wax prints sold in Malabo's market."],
    ["basket", "craft", "budget", "adults", "crafts", "Woven basket", "Made from forest fibres."],
  ]),
  country("ER", "Asmara's Italian modernist architecture and the Red Sea coast.", "Travel outside Asmara requires a permit.", [
    ["jebena", "decor", "budget", "adults", "drinks tradition crafts", "Jebena", "The clay coffee pot of the coffee ceremony."],
    ["netsela", "clothing", "mid", "adults", "fashion tradition", "Netsela", "A white cotton shawl."],
    ["basket", "decor", "budget", "adults", "crafts", "Woven basket", "Coiled and brightly dyed."],
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Gold and silver filigree", "From Asmara's jewellers."],
  ]),
  country("SZ", "The Umhlanga reed dance, game reserves and craft workshops.", "The lilangeni is tied to the South African rand, which is accepted everywhere.", [
    ["candles", "decor", "mid", "adults", "home-decor crafts", "Swazi candles", "Hand-moulded in animal shapes with swirling patterns."],
    ["glass", "decor", "mid", "adults", "home-decor crafts", "Ngwenya glass", "Blown from recycled bottles."],
    ["sisal-basket", "decor", "mid", "adults", "crafts home-decor", "Sisal basket", "Made by rural women's cooperatives."],
    ["batik", "art", "budget", "adults", "art crafts", "Batik", "Wall hangings with scenes of village life."],
  ]),
  country("GA", "Rainforest national parks where elephants walk on the beach.", "French is the working language, and prices are high by regional standards.", [
    ["soapstone", "decor", "mid", "adults", "art crafts", "Mbigou stone carving", "Soft grey stone carved into heads and figures."],
    ["mask", "decor", "mid", "adults", "art tradition", "Carved mask", "New white-faced masks in the Punu style."],
    ["fabric", "clothing", "budget", "adults", "fashion", "Printed fabric", "Wax prints from Libreville's market."],
    ["raffia", "craft", "budget", "adults", "crafts", "Raffia work", "Woven mats and bags."],
  ]),
  country("GM", "River cruises, birdwatching and Atlantic beaches.", "Bargaining is expected in the craft markets.", [
    ["batik", "clothing", "budget", "adults", "fashion crafts", "Batik", "Tie-dye and batik cloth, a Gambian speciality."],
    ["kora", "music", "premium", "adults", "music tradition", "Kora", "The 21-string harp of the griots."],
    ["carving", "decor", "budget", "adults", "art crafts", "Wood carving", "Masks and animals from the craft markets."],
    ["baobab", "food", "budget", "adults", "food nature", "Baobab powder", "The tangy fruit pulp used for juice."],
  ]),
  country("GN", "The Fouta Djallon highlands and a great drumming tradition.", ADVICE, [
    ["djembe", "music", "mid", "teens+", "music tradition", "Djembe", "Guinea is the heartland of the djembe."],
    ["lepi", "clothing", "mid", "adults", "fashion tradition crafts", "Lépi", "Indigo cloth of the Fulani."],
    ["basket", "craft", "budget", "adults", "crafts", "Woven basket", "From the highland markets."],
    ["carving", "decor", "mid", "adults", "art tradition", "Wood carving", "New carvings in the Baga style."],
  ]),
  country("GW", "The Bijagós islands and cashew orchards.", "Portuguese and Creole are spoken; little English or French.", [
    ["cashews", "food", "budget", "all", "food", "Cashew nuts", "The country's main crop."],
    ["panu-di-pinti", "clothing", "mid", "adults", "tradition crafts", "Panu di pinti", "Strip-woven ceremonial cloth."],
    ["carving", "decor", "mid", "adults", "art crafts", "Bijagó carving", "New figures from the islands."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "From the market in Bissau."],
  ]),
  country("LS", "A mountain kingdom lying entirely above 1,400 m, with ponies and blankets.", "The loti is tied to the South African rand, which is accepted everywhere.", [
    ["blanket", "clothing", "premium", "adults", "fashion tradition", "Basotho blanket", "A wool blanket worn as a cloak; the patterns have meanings."],
    ["mokorotlo", "clothing", "budget", "all", "tradition crafts", "Mokorotlo", "The conical straw hat on the national flag."],
    ["mohair", "decor", "mid", "adults", "home-decor crafts", "Mohair tapestry", "Woven by village cooperatives."],
    ["pottery", "decor", "budget", "adults", "crafts", "Pottery", "Stoneware from local studios."],
  ]),
  country("LR", "Surf beaches, rainforest and a history tied to freed American slaves.", "The US dollar is used alongside the Liberian dollar.", [
    ["country-cloth", "clothing", "mid", "adults", "tradition crafts", "Country cloth", "Handwoven strips sewn into cloth."],
    ["quilt", "decor", "mid", "adults", "home-decor crafts tradition", "Quilt", "Quilting came with the settlers and became a local art."],
    ["coffee", "drink", "budget", "adults", "drinks", "Liberian coffee", "From the country's own coffee species.", { soft: true }],
    ["carving", "decor", "mid", "adults", "art crafts", "Wood carving", "Newly carved masks and figures."],
  ]),
  country("LY", "The Roman city of Leptis Magna and the Sahara.", NO_TRAVEL, [
    ["dates", "food", "budget", "all", "sweets", "Dates", "From the oases of the south."],
    ["tuareg-silver", "jewelry", "mid", "adults", "jewelry tradition", "Tuareg silver", "Engraved desert jewellery."],
    ["slippers", "clothing", "mid", "adults", "crafts tradition", "Ghadames slippers", "Embroidered leather slippers from the oasis town."],
    ["olive-oil", "food", "mid", "adults", "cooking", "Olive oil", "From groves along the coast."],
  ]),
  country("MW", "Lake Malawi and a reputation as 'the warm heart of Africa'.", "Bargaining is expected at craft stalls.", [
    ["tea", "drink", "budget", "adults", "drinks", "Malawi tea", "From estates below Mount Mulanje.", { soft: true }],
    ["chiefs-chair", "decor", "premium", "adults", "home-decor crafts", "Chief's chair", "A carved two-piece folding chair."],
    ["chitenje", "clothing", "budget", "adults", "fashion", "Chitenje", "Printed cotton wrap."],
    ["pottery", "decor", "mid", "adults", "home-decor crafts", "Dedza pottery", "Hand-painted stoneware."],
    ["chilli-sauce", "food", "budget", "adults", "cooking", "Chilli sauce", "The country's famously hot peri-peri sauce."],
  ]),
  country("ML", "Timbuktu, the mud mosque of Djenné and desert blues.", "Most governments advise against travel.", [
    ["bogolan", "decor", "mid", "adults", "art crafts tradition", "Bogolan", "Cotton dyed with fermented mud."],
    ["tuareg-silver", "jewelry", "mid", "adults", "jewelry tradition", "Tuareg silver", "Crosses and amulets in engraved silver."],
    ["music", "music", "budget", "adults", "music", "Malian music recording", "Kora masters and desert blues bands."],
    ["shea-butter", "cosmetics", "budget", "adults", "beauty", "Shea butter", "Hand-processed in the villages."],
  ]),
  country("MR", "The Sahara, the long iron-ore train and ancient caravan towns.", "Alcohol is banned.", [
    ["silver", "jewelry", "mid", "adults", "jewelry crafts", "Silver jewellery", "With ebony and coloured inlay."],
    ["melhfa", "clothing", "mid", "adults", "fashion tradition", "Melhfa", "A long tie-dyed veil."],
    ["kiffa-beads", "jewelry", "mid", "adults", "jewelry crafts", "Kiffa beads", "Powder-glass beads made by hand."],
    ["tea-set", "decor", "mid", "adults", "drinks tradition", "Tea set", "A small pot and glasses for the three rounds of tea."],
  ]),
  country("MZ", "Indian Ocean beaches, prawns and marrabenta music.", "Sea-turtle products and ivory are illegal.", [
    ["capulana", "clothing", "budget", "adults", "fashion tradition", "Capulana", "A printed cotton wrap."],
    ["cashews", "food", "budget", "all", "food", "Cashew nuts", "Roasted and sold by the roadside."],
    ["piri-piri", "food", "budget", "adults", "cooking", "Piri-piri sauce", "Hot chilli sauce for prawns and chicken."],
    ["rum", "drink", "budget", "adults", "drinks", "Local rum", "Mixed with raspberry soda for the national cocktail."],
  ]),
  country("NE", "The Sahara, the mud-brick city of Agadez and Tuareg culture.", NO_TRAVEL, [
    ["agadez-cross", "jewelry", "mid", "adults", "jewelry tradition crafts", "Cross of Agadez", "A silver pendant; each town has its own form."],
    ["leather", "accessory", "mid", "adults", "crafts", "Tuareg leatherwork", "Dyed and fringed bags and boxes."],
    ["blanket", "decor", "mid", "adults", "crafts home-decor", "Djerma blanket", "Strip-woven cotton with bold patterns."],
    ["tea-glasses", "decor", "budget", "adults", "drinks tradition", "Tea glasses", "For the desert tea ritual."],
  ]),
  country("RW", "Mountain gorillas, green hills and a spotless capital.", "Plastic bags are banned and are confiscated on arrival.", [
    ["agaseke", "decor", "mid", "adults", "home-decor crafts tradition", "Agaseke", "A lidded 'peace basket' with a pointed top."],
    ["imigongo", "art", "mid", "adults", "art tradition", "Imigongo", "Geometric relief painting in black, white and red."],
    ["coffee", "drink", "budget", "adults", "drinks", "Rwandan coffee", "Bourbon arabica from washing stations in the hills.", { soft: true }],
    ["tea", "drink", "budget", "adults", "drinks", "Rwandan tea", "High-grown black tea.", { soft: true }],
  ]),
  country("ST", "Cocoa plantations, volcanic peaks and empty beaches.", "The dobra is pegged to the euro, and euros are widely accepted.", [
    ["chocolate", "food", "mid", "all", "sweets", "Chocolate", "Made on the islands from heirloom cocoa."],
    ["coffee", "drink", "mid", "adults", "drinks", "Coffee", "From the old plantation estates.", { soft: true }],
    ["pepper", "food", "budget", "adults", "cooking", "Pepper and vanilla", "Organic spices grown on Príncipe."],
    ["carving", "decor", "budget", "adults", "art crafts", "Wood carving", "Figures by local artisans."],
  ]),
  country("SL", "White-sand beaches, diamonds and a resilient people.", "Bargaining is expected in the markets.", [
    ["gara", "clothing", "mid", "adults", "fashion crafts", "Gara cloth", "Tie-dyed cotton, a local speciality."],
    ["country-cloth", "decor", "mid", "adults", "tradition crafts", "Country cloth", "Thick handwoven strip cloth."],
    ["basket", "decor", "budget", "adults", "crafts", "Shukublai basket", "Coiled baskets of the Temne."],
    ["carving", "decor", "mid", "adults", "art crafts", "Wood carving", "New carvings in traditional styles."],
  ]),
  country("SO", "Africa's longest mainland coastline, frankincense and poetry.", NO_TRAVEL, [
    ["frankincense", "cosmetics", "budget", "adults", "beauty tradition", "Frankincense", "Somalia is a leading source."],
    ["macawiis", "clothing", "budget", "adults", "fashion tradition", "Macawiis", "A patterned sarong worn by men."],
    ["basket", "decor", "budget", "adults", "crafts", "Woven basket", "Tight baskets once used to carry milk."],
    ["tea-spices", "food", "budget", "adults", "cooking drinks", "Tea spices", "Cardamom, cinnamon and cloves for spiced tea."],
  ]),
  country("SS", "The Sudd wetlands and one of the world's great wildlife migrations.", NO_TRAVEL, [
    ["beadwork", "jewelry", "budget", "adults", "jewelry tradition crafts", "Beadwork", "Bright glass-bead jewellery."],
    ["basket", "decor", "budget", "adults", "crafts", "Woven basket", "From market cooperatives in Juba."],
    ["stool", "decor", "mid", "adults", "crafts tradition", "Carved stool", "A small wooden headrest-stool."],
    ["fabric", "clothing", "budget", "adults", "fashion", "Printed fabric", "Cotton wraps."],
  ]),
  country("SD", "The pyramids of Meroë and the meeting of the Blue and White Nile.", NO_TRAVEL, [
    ["karkade", "food", "budget", "adults", "drinks cooking", "Karkade", "Dried hibiscus, a major export."],
    ["toub", "clothing", "mid", "adults", "fashion tradition", "Toub", "The long wrapped cloth worn by women."],
    ["sandals", "clothing", "mid", "adults", "crafts tradition", "Markoob", "Handmade leather slippers."],
    ["bakhoor", "cosmetics", "budget", "adults", "beauty tradition", "Bakhoor", "Scented wood for perfuming the home."],
  ]),
  country("TG", "Voodoo markets, green hills and palm-lined beaches.", "Bargaining is expected in the markets.", [
    ["batik", "art", "budget", "adults", "art crafts", "Batik", "Wall hangings from the artisan centre in Kpalimé."],
    ["wax-fabric", "clothing", "budget", "adults", "fashion", "Wax-print fabric", "Lomé's market is a regional hub for it."],
    ["coffee", "drink", "budget", "adults", "drinks", "Coffee and cocoa", "From the plateau region.", { soft: true }],
    ["carving", "decor", "mid", "adults", "art crafts", "Wood carving", "Figures and stools by local carvers."],
  ]),
  country("UG", "Mountain gorillas, the source of the Nile and Lake Victoria.", "Gorilla permits are limited and should be booked months ahead.", [
    ["bark-cloth", "decor", "mid", "adults", "crafts tradition art", "Bark cloth", "Beaten from fig-tree bark, a UNESCO-listed craft."],
    ["coffee", "drink", "budget", "adults", "drinks", "Ugandan coffee", "Arabica from Mount Elgon.", { soft: true }],
    ["kitenge", "clothing", "budget", "adults", "fashion", "Kitenge", "Printed cotton fabric."],
    ["basket", "decor", "budget", "adults", "crafts home-decor", "Woven basket", "Coiled from raffia and banana fibre."],
    ["gin", "drink", "budget", "adults", "drinks", "Waragi", "Ugandan gin."],
  ]),
  country("ZM", "Victoria Falls, walking safaris and copper.", "Many visitors need a visa; one combined visa covers Zambia and Zimbabwe.", [
    ["copper", "decor", "mid", "adults", "home-decor crafts", "Copper craft", "Plates and jewellery from the Copperbelt."],
    ["chitenge", "clothing", "budget", "adults", "fashion", "Chitenge", "Printed cotton wrap."],
    ["basket", "decor", "mid", "adults", "crafts home-decor", "Tonga basket", "Flat woven baskets with geometric designs."],
    ["emerald", "jewelry", "premium", "adults", "jewelry", "Zambian emerald", "Buy only with a certificate."],
  ]),
  country("ZW", "Victoria Falls, the ruins of Great Zimbabwe and stone sculpture.", "US dollars in small notes are the most practical way to pay.", [
    ["shona-sculpture", "art", "premium", "adults", "art crafts", "Shona stone sculpture", "Carved from serpentine and springstone."],
    ["basket", "decor", "mid", "adults", "crafts home-decor", "Binga basket", "Woven by Tonga women near Lake Kariba."],
    ["batik", "art", "budget", "adults", "art crafts", "Batik", "Cloth paintings of wildlife."],
    ["mbira", "music", "mid", "adults", "music tradition", "Mbira", "A thumb piano with metal keys."],
  ]),
];
