import { country, type CountrySeed } from "../define";

const REEF = "Coral, shells and sea-turtle products cannot be taken out.";

export const americas: CountrySeed[] = [
  country("US", "National parks, New York, Hollywood, jazz and road trips.", "Sales tax is added at the till and varies by state; most visitors need an ESTA or a visa before travelling.", [
    ["baseball-cap", "clothing", "budget", "all", "sports fashion", "Baseball cap", "The cap of a local team."],
    ["jeans", "clothing", "mid", "teens+", "fashion", "Blue jeans", "American denim brands cost less at home."],
    ["bourbon", "drink", "mid", "adults", "drinks", "Bourbon", "Corn whiskey from Kentucky.", { region: "Kentucky" }],
    ["space-souvenir", "toy", "budget", "kids", "science toys", "Space souvenir", "Freeze-dried ice cream and mission patches from a space centre."],
    ["candy", "food", "budget", "all", "sweets", "American candy", "Peanut-butter cups and other sweets hard to find abroad."],
    ["park-poster", "art", "budget", "all", "nature collectibles art", "National park poster", "Retro-style prints sold in park visitor centres."],
    ["turquoise", "jewelry", "mid", "adults", "jewelry crafts tradition", "Turquoise jewellery", "Navajo and Pueblo silverwork; look for the artist's hallmark.", { region: "New Mexico" }],
    ["hot-sauce", "food", "budget", "adults", "cooking", "Hot sauce", "Louisiana pepper sauce or a small-batch local one."],
  ]),
  country("CA", "The Rockies, maple syrup, ice hockey and vast wilderness.", "Sales taxes are added at the till; visa-exempt travellers arriving by air need an eTA.", [
    ["maple-syrup", "food", "budget", "all", "sweets food cooking", "Maple syrup", "Graded by colour, from golden to very dark."],
    ["hockey-jersey", "clothing", "premium", "all", "sports", "Hockey jersey", "The sweater of a Canadian team."],
    ["ice-wine", "drink", "premium", "adults", "drinks", "Ice wine", "Sweet wine from grapes frozen on the vine.", { region: "Ontario" }],
    ["smoked-salmon", "food", "mid", "adults", "food", "Smoked salmon", "Sold in travel packs that need no refrigeration.", { region: "British Columbia" }],
    ["inuit-carving", "art", "premium", "adults", "art tradition", "Inuit carving", "Stone sculpture; the Igloo tag certifies authentic work."],
    ["mountie-bear", "toy", "budget", "child", "toys humor", "Mountie bear", "A plush bear in the red police uniform."],
    ["maple-cookies", "food", "budget", "all", "sweets", "Maple cream cookies", "Leaf-shaped sandwich biscuits."],
    ["toque", "clothing", "budget", "all", "fashion", "Toque", "A knitted winter hat.", { months: [11, 12, 1, 2, 3] }],
  ]),
  country("MX", "Maya and Aztec ruins, tacos, mariachi and the Day of the Dead.", "Pre-Hispanic artefacts cannot be exported, and products from sea turtles and black coral are illegal.", [
    ["talavera", "decor", "mid", "adults", "home-decor crafts", "Talavera pottery", "Tin-glazed ceramics from Puebla with a certified mark.", { region: "Puebla" }],
    ["tequila", "drink", "mid", "adults", "drinks", "Tequila", "Choose one labelled 100% agave."],
    ["mezcal", "drink", "mid", "adults", "drinks", "Mezcal", "Smoky agave spirit from small producers in Oaxaca.", { region: "Oaxaca" }],
    ["alebrije", "art", "mid", "all", "art crafts collectibles", "Alebrije", "A fantastical carved and painted creature.", { region: "Oaxaca" }],
    ["catrina", "decor", "budget", "teens+", "tradition art collectibles", "Catrina figure", "The elegant skeleton of the Day of the Dead.", { months: [10, 11] }],
    ["silver", "jewelry", "mid", "adults", "jewelry crafts", "Taxco silver", "Look for the .925 stamp."],
    ["chocolate", "food", "budget", "all", "sweets cooking", "Oaxacan chocolate", "Stone-ground with cinnamon, for drinking."],
    ["lucha-mask", "toy", "budget", "kids", "humor toys sports", "Lucha libre mask", "A wrestler's colourful mask."],
  ]),
  country("AR", "Tango, steak, Patagonia, football and mate.", "Exchange rates and payment rules change often; check the current situation before changing money.", [
    ["mate-set", "drink", "budget", "adults", "drinks tradition", "Mate set", "A gourd, a metal straw and a bag of yerba.", { soft: true }],
    ["dulce-de-leche", "food", "budget", "all", "sweets", "Dulce de leche", "Milk caramel in a jar."],
    ["alfajores", "food", "budget", "all", "sweets", "Alfajores", "Sandwich biscuits filled with dulce de leche."],
    ["malbec", "drink", "mid", "adults", "drinks", "Malbec", "Red wine from Mendoza.", { region: "Mendoza" }],
    ["leather", "accessory", "premium", "adults", "fashion", "Leather goods", "Belts, wallets and jackets."],
    ["football-shirt", "clothing", "mid", "all", "sports", "Football shirt", "The sky-blue and white stripes or a Buenos Aires club."],
    ["tango", "music", "budget", "adults", "music", "Tango recording", "From Gardel to Piazzolla."],
    ["rhodochrosite", "jewelry", "mid", "adults", "jewelry", "Rhodochrosite", "The pink 'Inca rose', Argentina's national stone."],
  ]),
  country("CL", "The Atacama desert, Patagonia, wine and Easter Island.", "Agricultural controls are strict: declare all food and plant products on arrival.", [
    ["carmenere", "drink", "mid", "adults", "drinks", "Carménère", "A grape that survived in Chile after dying out in France."],
    ["lapis", "jewelry", "mid", "adults", "jewelry", "Lapis lazuli", "Chile is one of the few sources of the blue stone."],
    ["pisco", "drink", "mid", "adults", "drinks", "Pisco", "Grape brandy from the Elqui valley."],
    ["copper", "decor", "budget", "adults", "home-decor crafts", "Copper craft", "From the world's largest copper producer."],
    ["moai", "decor", "budget", "all", "collectibles history", "Moai figure", "A model of the Easter Island statues."],
    ["merken", "food", "budget", "adults", "cooking", "Merkén", "Smoked chilli seasoning of the Mapuche."],
    ["wool-sweater", "clothing", "mid", "adults", "fashion", "Chiloé wool sweater", "Thick hand-knits from the southern islands."],
  ]),
  country("PE", "Machu Picchu, the Andes, the Amazon and a celebrated cuisine.", "Coca tea and leaves are legal in Peru but prohibited at most other borders; pre-Columbian artefacts cannot be exported.", [
    ["alpaca", "clothing", "premium", "adults", "fashion", "Alpaca sweater", "Very cheap 'alpaca' in markets is usually acrylic."],
    ["chullo", "clothing", "budget", "all", "fashion tradition", "Chullo", "A knitted hat with ear flaps."],
    ["pisco", "drink", "mid", "adults", "drinks", "Pisco", "Grape brandy, the base of the pisco sour."],
    ["retablo", "art", "mid", "adults", "art tradition crafts", "Retablo", "A painted box of tiny figures from Ayacucho."],
    ["textile", "decor", "mid", "adults", "home-decor crafts tradition", "Andean textile", "Woven on backstrap looms near Cusco.", { region: "Cusco" }],
    ["chocolate", "food", "budget", "all", "sweets", "Peruvian chocolate", "From Amazonian cocoa."],
    ["pucara-bull", "decor", "budget", "adults", "tradition home-decor", "Pucará bull", "Ceramic bulls placed on rooftops for luck."],
    ["panpipe", "music", "budget", "kids", "music", "Zampoña", "Andean panpipes."],
  ]),
  country("CO", "Coffee, emeralds, salsa, the Caribbean coast and Gabriel García Márquez.", "Coca tea and coca sweets sold legally there are prohibited at most other borders.", [
    ["coffee", "drink", "budget", "adults", "drinks cooking", "Colombian coffee", "Single-estate beans from the coffee region.", { soft: true }],
    ["emerald", "jewelry", "premium", "adults", "jewelry", "Emerald", "Buy from an established jeweller with a certificate."],
    ["mochila", "accessory", "mid", "adults", "fashion crafts tradition", "Wayuu mochila", "A crocheted bag; each takes weeks to make.", { region: "La Guajira" }],
    ["sombrero-vueltiao", "clothing", "mid", "adults", "tradition fashion", "Sombrero vueltiao", "The black-and-white woven hat, a national symbol."],
    ["ruana", "clothing", "mid", "adults", "fashion", "Ruana", "A wool poncho from the Andes."],
    ["artist-shirt", "clothing", "budget", "teens+", "music fashion", "Colombian music T-shirt", "A shirt or album by a local artist, from vallenato and cumbia legends to today's pop and reggaeton stars."],
    ["bocadillo", "food", "budget", "all", "sweets", "Bocadillo", "Guava paste wrapped in leaves."],
    ["chiva", "decor", "budget", "kids", "collectibles toys", "Miniature chiva", "A model of the painted country buses."],
  ]),
  country("CU", "Classic cars, cigars, rum, salsa and colonial Havana.", "Cigars need the official receipt and holographic seal to pass customs, and US rules restrict what American travellers may bring back.", [
    ["cigars", "accessory", "premium", "adults", "tradition collectibles", "Cuban cigars", "Buy only in official shops; street cigars are fakes."],
    ["rum", "drink", "mid", "adults", "drinks", "Cuban rum", "Aged rum from Havana or Santiago."],
    ["coffee", "drink", "budget", "adults", "drinks", "Cuban coffee", "Dark-roasted beans from the Sierra Maestra.", { soft: true }],
    ["guayabera", "clothing", "mid", "adults", "fashion", "Guayabera", "The pleated four-pocket shirt."],
    ["son", "music", "budget", "adults", "music", "Son cubano recording", "The music behind salsa."],
    ["painting", "art", "mid", "adults", "art", "Street-gallery painting", "Artworks need an export stamp, which galleries provide."],
  ]),
  country("CR", "Rainforests, volcanoes, sloths and 'pura vida'.", "Shells, corals and wildlife products may not be taken out.", [
    ["coffee", "drink", "budget", "adults", "drinks", "Costa Rican coffee", "Beans from Tarrazú or the Central Valley.", { soft: true }],
    ["oxcart", "decor", "mid", "all", "tradition crafts collectibles", "Painted oxcart", "A miniature of the decorated carts of Sarchí."],
    ["salsa", "food", "budget", "adults", "cooking", "Vegetable sauce", "The brown table sauce found in every home."],
    ["chorreador", "decor", "budget", "adults", "drinks home-decor", "Chorreador", "A wooden stand with a cloth filter for brewing coffee."],
    ["sloth", "toy", "budget", "child", "toys nature", "Plush sloth", "The animal everyone hopes to see."],
  ]),
  country("DO", "Caribbean beaches, merengue, baseball and the first European city in the Americas.", "Cheap 'amber' and 'larimar' on the beach are often plastic; buy from established shops.", [
    ["larimar", "jewelry", "mid", "adults", "jewelry", "Larimar", "A sky-blue stone found only here."],
    ["amber", "jewelry", "mid", "adults", "jewelry nature", "Dominican amber", "Clear amber, sometimes with insects inside."],
    ["rum", "drink", "mid", "adults", "drinks", "Dominican rum", "Smooth aged rum."],
    ["mamajuana", "drink", "mid", "adults", "drinks tradition", "Mamajuana", "Rum, wine and honey steeped with bark and herbs."],
    ["coffee", "drink", "budget", "adults", "drinks", "Dominican coffee", "From the central mountains.", { soft: true }],
    ["faceless-doll", "decor", "mid", "adults", "tradition crafts", "Faceless doll", "A ceramic figure representing the island's mixed heritage."],
  ]),
  country("JM", "Reggae, Blue Mountain coffee, jerk cooking and sprinters.", "Cannabis products sold to tourists cannot legally be taken out of the country.", [
    ["coffee", "drink", "premium", "adults", "drinks", "Blue Mountain coffee", "Among the most expensive coffees in the world.", { soft: true }],
    ["rum", "drink", "mid", "adults", "drinks", "Jamaican rum", "Full-flavoured pot-still rum."],
    ["jerk-seasoning", "food", "budget", "adults", "cooking", "Jerk seasoning", "Allspice and Scotch-bonnet pepper paste."],
    ["reggae", "music", "budget", "adults", "music", "Reggae vinyl", "From Kingston's record shops."],
    ["tam", "clothing", "budget", "teens+", "fashion", "Crochet tam", "In red, gold and green."],
  ]),
  country("EC", "The Galápagos, the Andes, the equator line and Amazon rainforest.", "Nothing natural may be taken from the Galápagos: no shells, sand or lava.", [
    ["panama-hat", "clothing", "premium", "adults", "fashion crafts tradition", "Toquilla straw hat", "The 'Panama hat' is in fact woven in Ecuador."],
    ["chocolate", "food", "mid", "all", "sweets", "Fine chocolate", "From the prized Arriba cocoa."],
    ["tagua", "jewelry", "budget", "all", "jewelry nature crafts", "Tagua jewellery", "Carved from a palm nut known as vegetable ivory."],
    ["otavalo-textile", "decor", "mid", "adults", "crafts home-decor", "Otavalo textile", "From the famous Saturday market."],
    ["tigua", "art", "mid", "adults", "art tradition", "Tigua painting", "Andean scenes painted on sheepskin."],
  ]),
  country("BO", "The Uyuni salt flats, La Paz in the clouds and Lake Titicaca.", "Coca leaves and tea are legal in Bolivia but prohibited at most other borders.", [
    ["aguayo", "decor", "mid", "adults", "crafts tradition", "Aguayo", "Striped woven cloth used to carry everything."],
    ["alpaca", "clothing", "mid", "adults", "fashion", "Alpaca knitwear", "Sweaters, gloves and scarves."],
    ["salt", "food", "budget", "adults", "cooking", "Uyuni salt", "From the world's largest salt flat."],
    ["charango", "music", "premium", "adults", "music", "Charango", "A small ten-stringed Andean lute."],
    ["ekeko", "decor", "budget", "all", "tradition humor", "Ekeko", "A god of abundance loaded with miniatures, sold at the January fair.", { months: [1] }],
  ]),
  country("PA", "The Canal, rainforest and two oceans an hour apart.", "The US dollar is used alongside balboa coins.", [
    ["mola", "art", "mid", "adults", "art crafts tradition", "Mola", "Layered reverse-appliqué panels made by Guna women."],
    ["coffee", "drink", "premium", "adults", "drinks", "Geisha coffee", "A prized variety grown in the Chiriquí highlands.", { soft: true }],
    ["rum", "drink", "mid", "adults", "drinks", "Panamanian rum", "Aged rum."],
    ["tagua", "decor", "budget", "all", "crafts", "Tagua carving", "Tiny animals carved from palm nuts."],
    ["chaquira", "jewelry", "budget", "adults", "jewelry tradition", "Chaquira", "A wide beaded collar of the Ngäbe people."],
  ]),
  country("GT", "The Maya ruins of Tikal, volcanoes, Lake Atitlán and colourful markets.", "Maya artefacts cannot be exported.", [
    ["huipil", "clothing", "mid", "adults", "fashion crafts tradition", "Huipil", "A handwoven blouse; each village has its own design."],
    ["worry-dolls", "toy", "budget", "kids", "toys tradition crafts", "Worry dolls", "Tiny dolls to tell your worries to before sleep."],
    ["coffee", "drink", "budget", "adults", "drinks", "Guatemalan coffee", "From Antigua or Huehuetenango.", { soft: true }],
    ["jade", "jewelry", "mid", "adults", "jewelry history", "Jade", "The stone the Maya valued above gold."],
    ["rum", "drink", "premium", "adults", "drinks", "Aged rum", "Matured at altitude."],
  ]),
  country("AG", "A beach for every day of the year, and sailing week.", REEF, [
    ["rum", "drink", "mid", "adults", "drinks", "Antiguan rum", "Aged rum from the island distillery."],
    ["pineapple-jam", "food", "budget", "all", "sweets", "Black pineapple jam", "From the island's very sweet pineapple."],
    ["hot-sauce", "food", "budget", "adults", "cooking", "Hot sauce", "A long-established local brand."],
    ["pottery", "decor", "budget", "adults", "crafts", "Sea View Farm pottery", "Unglazed clay pots made in a village tradition."],
  ]),
  country("BS", "Turquoise water, swimming pigs and the Junkanoo parade.", "A conch shell may be restricted at your home border; check before packing one.", [
    ["straw-bag", "accessory", "mid", "adults", "fashion crafts", "Straw bag", "Plaited palm, from the straw market."],
    ["rum-cake", "food", "budget", "adults", "sweets", "Rum cake", "Vacuum-packed and long-lasting."],
    ["batik", "clothing", "mid", "adults", "fashion crafts", "Androsia batik", "Hand-dyed cotton from Andros."],
    ["guava-jam", "food", "budget", "all", "sweets", "Guava jam", "The filling of the local duff pudding."],
  ]),
  country("BB", "The birthplace of rum, cricket and beaches.", REEF, [
    ["rum", "drink", "mid", "adults", "drinks", "Barbados rum", "From distilleries working since the 1700s."],
    ["pepper-sauce", "food", "budget", "adults", "cooking", "Bajan pepper sauce", "Mustard-yellow and very hot."],
    ["pottery", "decor", "mid", "adults", "home-decor crafts", "Hand-painted pottery", "Bright tableware from island studios."],
    ["cricket-shirt", "clothing", "mid", "all", "sports", "Cricket shirt", "West Indies colours."],
  ]),
  country("BZ", "The barrier reef, the Blue Hole and Maya ruins.", REEF, [
    ["hot-sauce", "food", "budget", "adults", "cooking", "Habanero hot sauce", "The carrot-based sauce on every table."],
    ["chocolate", "food", "mid", "all", "sweets", "Maya chocolate", "Made from cocoa grown in the Toledo district."],
    ["slate-carving", "art", "mid", "adults", "art crafts history", "Slate carving", "Maya motifs carved in local slate."],
    ["basket", "decor", "mid", "adults", "crafts", "Jippi jappa basket", "Fine palm baskets woven by Maya women."],
  ]),
  country("DM", "'The nature island': rainforest, hot springs and whale watching.", "Not to be confused with the Dominican Republic.", [
    ["basket", "decor", "mid", "adults", "crafts tradition", "Kalinago basket", "Woven from larouma reed by the island's indigenous people."],
    ["bay-rum", "cosmetics", "budget", "adults", "beauty", "Bay rum", "A spiced cologne distilled from bay leaves."],
    ["soap", "cosmetics", "budget", "adults", "beauty", "Coconut soap", "Made on the island."],
    ["rum", "drink", "budget", "adults", "drinks", "Local rum", "Often infused with spices."],
  ]),
  country("SV", "Volcanoes, surf and pupusas.", "The US dollar is the currency.", [
    ["la-palma", "art", "budget", "all", "art crafts", "La Palma craft", "Wood painted in the naive style of Fernando Llort."],
    ["coffee", "drink", "budget", "adults", "drinks", "Salvadoran coffee", "From volcanic slopes.", { soft: true }],
    ["indigo", "clothing", "mid", "adults", "fashion crafts", "Indigo textile", "Dyed with locally grown añil."],
    ["hammock", "decor", "mid", "adults", "home-decor crafts", "Hammock", "Woven in the town of Concepción Quezaltepeque."],
  ]),
  country("GD", "'The spice island': nutmeg, cocoa and waterfalls.", REEF, [
    ["spices", "food", "budget", "adults", "cooking", "Spice basket", "Nutmeg, mace, cinnamon and cloves in a woven basket."],
    ["chocolate", "food", "mid", "all", "sweets", "Grenadian chocolate", "Made on the island from tree to bar."],
    ["rum", "drink", "mid", "adults", "drinks", "Grenadian rum", "Some is too strong to carry on a plane; check the label."],
    ["nutmeg-jam", "food", "budget", "all", "sweets", "Nutmeg jam", "Made from the fruit around the nut."],
  ]),
  country("GY", "Kaieteur Falls, rainforest and Demerara rum.", "English is the official language, unique in South America.", [
    ["rum", "drink", "mid", "adults", "drinks", "Demerara rum", "Aged in wooden stills."],
    ["sugar", "food", "budget", "all", "sweets cooking", "Demerara sugar", "The golden sugar named after the region."],
    ["basket", "decor", "mid", "adults", "crafts tradition", "Tibisiri basket", "Woven from palm fibre by Amerindian communities."],
    ["cassareep", "food", "budget", "adults", "cooking", "Cassareep", "Cassava sauce, the base of pepperpot."],
  ]),
  country("HT", "The first Black republic, vivid painting and the Citadelle.", "Most governments advise against all travel.", [
    ["painting", "art", "mid", "adults", "art", "Naive painting", "Brightly coloured market and jungle scenes."],
    ["metal-art", "decor", "mid", "adults", "art crafts home-decor", "Cut-metal art", "Sculpture hammered from old oil drums."],
    ["rum", "drink", "mid", "adults", "drinks", "Haitian rum", "Distilled from cane juice."],
    ["sequin-flag", "art", "premium", "adults", "art tradition", "Sequin flag", "A beaded banner from the Vodou tradition."],
    ["coffee", "drink", "budget", "adults", "drinks", "Haitian coffee", "Mountain-grown arabica.", { soft: true }],
  ]),
  country("HN", "The Maya ruins of Copán, diving in the Bay Islands and coffee.", "Check your government's travel advice before going.", [
    ["coffee", "drink", "budget", "adults", "drinks", "Honduran coffee", "From Copán and Marcala.", { soft: true }],
    ["lenca-pottery", "decor", "mid", "adults", "home-decor crafts tradition", "Lenca pottery", "Black-and-white etched ceramics."],
    ["cigars", "accessory", "mid", "adults", "tradition", "Honduran cigars", "Hand-rolled in the west of the country."],
    ["chocolate", "food", "budget", "all", "sweets", "Chocolate", "From local cocoa."],
  ]),
  country("NI", "Lakes, volcanoes and colonial Granada.", "Check your government's travel advice before going.", [
    ["rum", "drink", "mid", "adults", "drinks", "Nicaraguan rum", "Aged at the foot of a volcano."],
    ["coffee", "drink", "budget", "adults", "drinks", "Nicaraguan coffee", "From Matagalpa and Jinotega.", { soft: true }],
    ["hammock", "decor", "mid", "adults", "home-decor crafts", "Masaya hammock", "Handwoven cotton hammocks."],
    ["pottery", "decor", "mid", "adults", "home-decor crafts art", "San Juan de Oriente pottery", "Burnished ceramics with pre-Columbian motifs."],
  ]),
  country("PY", "Jesuit missions, the Chaco and ice-cold tereré.", "Guaraní is spoken alongside Spanish by most of the population.", [
    ["nanduti", "craft", "mid", "adults", "crafts tradition art", "Ñandutí", "'Spider-web' lace in bright colours."],
    ["terere-set", "drink", "budget", "adults", "drinks tradition", "Tereré set", "A horn cup and straw for cold mate.", { soft: true }],
    ["ao-poi", "clothing", "mid", "adults", "fashion crafts", "Ao po'i shirt", "Light embroidered cotton."],
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Silver filigree", "From the town of Luque."],
  ]),
  country("KN", "A volcanic twin-island state with a hilltop fortress.", REEF, [
    ["batik", "clothing", "mid", "adults", "fashion crafts", "Batik", "Made at a studio in old plantation gardens."],
    ["rum", "drink", "mid", "adults", "drinks", "Local rum", "Cane spirit."],
    ["hot-sauce", "food", "budget", "adults", "cooking", "Hot sauce", "Scotch-bonnet pepper sauce."],
    ["guava-cheese", "food", "budget", "all", "sweets", "Guava cheese", "Firm guava sweets."],
  ]),
  country("LC", "The twin Pitons, volcanic beaches and a jazz festival.", REEF, [
    ["banana-ketchup", "food", "budget", "all", "cooking", "Banana ketchup", "A sweet-spicy sauce."],
    ["rum", "drink", "mid", "adults", "drinks", "Saint Lucian rum", "Blended aged rum."],
    ["cocoa-sticks", "food", "budget", "adults", "drinks cooking", "Cocoa sticks", "Rolled cocoa for making 'cocoa tea'."],
    ["batik", "clothing", "mid", "adults", "fashion crafts", "Batik", "Hand-printed island fabric."],
  ]),
  country("VC", "Sailing the Grenadines and black-sand beaches.", REEF, [
    ["rum", "drink", "budget", "adults", "drinks", "Strong rum", "Too strong for many airlines; check the label."],
    ["arrowroot", "food", "budget", "all", "cooking sweets", "Arrowroot biscuits", "The island was once the world's arrowroot supplier."],
    ["model-boat", "decor", "premium", "adults", "crafts collectibles", "Bequia model boat", "Handmade by the island's boatbuilders."],
    ["hot-sauce", "food", "budget", "adults", "cooking", "Hot sauce", "Local pepper sauce."],
  ]),
  country("SR", "Dutch colonial Paramaribo and untouched rainforest.", "Dutch is the official language.", [
    ["maroon-carving", "art", "mid", "adults", "art crafts tradition", "Maroon wood carving", "Interlaced designs carved by descendants of escaped slaves."],
    ["pangi", "clothing", "budget", "adults", "fashion tradition", "Pangi", "Striped or embroidered Maroon wrap cloth."],
    ["rum", "drink", "mid", "adults", "drinks", "Surinamese rum", "Aged cane rum."],
    ["sambal", "food", "budget", "adults", "cooking", "Sambal", "Chilli relish from the Javanese-Surinamese kitchen."],
  ]),
  country("TT", "Carnival, steelpan, calypso and soca.", "Carnival falls on the Monday and Tuesday before Ash Wednesday.", [
    ["steelpan", "music", "mid", "kids", "music tradition", "Miniature steelpan", "The instrument invented here from oil drums."],
    ["bitters", "food", "budget", "adults", "cooking drinks", "Aromatic bitters", "The cocktail ingredient made in Port of Spain."],
    ["rum", "drink", "mid", "adults", "drinks", "Trinidad rum", "Aged rum."],
    ["pepper-sauce", "food", "budget", "adults", "cooking", "Pepper sauce", "Made with the island's very hot peppers."],
    ["chocolate", "food", "mid", "all", "sweets", "Trinitario chocolate", "From the cocoa variety born on the island."],
  ]),
  country("UY", "Mate, the beaches of Punta del Este, beef and laid-back Montevideo.", "Foreign cards often get a VAT discount in restaurants.", [
    ["mate-set", "drink", "budget", "adults", "drinks tradition", "Mate set", "Uruguayans carry theirs everywhere.", { soft: true }],
    ["dulce-de-leche", "food", "budget", "all", "sweets", "Dulce de leche", "Milk caramel."],
    ["amethyst", "jewelry", "mid", "adults", "jewelry nature", "Amethyst", "From the mines of Artigas."],
    ["tannat", "drink", "mid", "adults", "drinks", "Tannat", "The country's signature red wine."],
    ["wool", "clothing", "mid", "adults", "fashion", "Merino knitwear", "From a country with more sheep than people."],
  ]),
  country("VE", "Angel Falls, the Caribbean coast and cacao.", "Check your government's travel advice before going.", [
    ["chocolate", "food", "mid", "all", "sweets", "Venezuelan chocolate", "From some of the world's finest cocoa."],
    ["rum", "drink", "mid", "adults", "drinks", "Aged rum", "Matured for at least two years by law."],
    ["cuatro", "music", "premium", "adults", "music", "Cuatro", "A small four-stringed guitar."],
    ["hammock", "decor", "mid", "adults", "home-decor crafts", "Chinchorro", "A net-like woven hammock."],
    ["coffee", "drink", "budget", "adults", "drinks", "Venezuelan coffee", "From the Andes.", { soft: true }],
  ]),
  country("PR", "Old San Juan, salsa, reggaeton and bioluminescent bays.", "A US territory: the dollar is used and US entry rules apply.", [
    ["rum", "drink", "mid", "adults", "drinks", "Puerto Rican rum", "Distillery tours end in the shop."],
    ["coffee", "drink", "budget", "adults", "drinks", "Puerto Rican coffee", "From the central mountains.", { soft: true }],
    ["vejigante-mask", "art", "mid", "adults", "art tradition crafts", "Vejigante mask", "A horned carnival mask."],
    ["santos", "art", "mid", "adults", "art tradition", "Santos carving", "Small hand-carved figures of saints."],
    ["artist-shirt", "clothing", "budget", "teens+", "music fashion", "Music T-shirt", "From the island that gave the world salsa stars and reggaeton."],
  ]),
  country("GL", "Icebergs, the ice sheet and Inuit culture.", "Items from whale, seal or polar bear need CITES permits and are banned from import into many countries.", [
    ["tupilak", "art", "premium", "adults", "art tradition", "Tupilak", "A small carved spirit figure; choose one in antler or stone."],
    ["beadwork", "jewelry", "mid", "adults", "jewelry crafts tradition", "Beadwork", "Like the collar of the national costume."],
    ["qiviut", "clothing", "premium", "adults", "fashion", "Qiviut hat", "Knitted from musk-ox underwool."],
    ["herbal-tea", "drink", "budget", "adults", "drinks nature", "Arctic herbal tea", "Made from tundra plants.", { soft: true }],
  ]),
  country("BM", "Pink-sand beaches, pastel houses and Bermuda shorts.", "Rental cars are not available to visitors; scooters and small electric vehicles are.", [
    ["shorts", "clothing", "mid", "adults", "fashion humor", "Bermuda shorts", "Worn with knee socks and a blazer."],
    ["rum-cake", "food", "budget", "adults", "sweets", "Rum cake", "Soaked in black rum."],
    ["rum", "drink", "mid", "adults", "drinks", "Black rum", "The base of the Dark 'n' Stormy."],
    ["pepper-sauce", "food", "budget", "adults", "cooking", "Sherry pepper sauce", "A spiced sherry splashed on fish chowder."],
  ]),
  country("AW", "Constant sunshine, trade winds and white beaches.", "The island lies outside the hurricane belt.", [
    ["aloe", "cosmetics", "budget", "adults", "beauty", "Aloe products", "Aloe has been grown here since the 1800s."],
    ["hot-sauce", "food", "budget", "adults", "cooking", "Papaya hot sauce", "A fiery local relish."],
    ["rum", "drink", "mid", "adults", "drinks", "Local rum", "And the mix for the island's cocktail."],
    ["tile", "decor", "budget", "adults", "home-decor", "Delft-style tile", "A reminder of the Dutch connection."],
  ]),
  country("CW", "The pastel Dutch waterfront of Willemstad and the blue liqueur.", "The island lies outside the hurricane belt.", [
    ["blue-liqueur", "drink", "mid", "adults", "drinks", "Curaçao liqueur", "The original, made from the peel of the local laraha orange."],
    ["chichi", "art", "mid", "adults", "art collectibles", "Chichi figure", "A brightly painted sculpture of a 'big sister'."],
    ["aloe", "cosmetics", "budget", "adults", "beauty", "Aloe products", "From the island's aloe plantation."],
    ["house-miniature", "decor", "budget", "all", "collectibles", "Waterfront house miniature", "A model of the coloured gabled houses."],
  ]),
  country("KY", "Seven Mile Beach, diving and offshore finance.", "Sea-turtle products are sold locally but are illegal to import almost everywhere.", [
    ["rum-cake", "food", "budget", "adults", "sweets", "Rum cake", "The islands' best-known export."],
    ["caymanite", "jewelry", "mid", "adults", "jewelry nature", "Caymanite", "A banded stone found only here."],
    ["rum", "drink", "mid", "adults", "drinks", "Local rum", "Some is aged in casks under the sea."],
    ["sea-salt", "food", "budget", "adults", "cooking", "Sea salt", "Hand-harvested."],
  ]),
];
