import { country, type CountrySeed } from "../define";

export const asia: CountrySeed[] = [
  country("CN", "The Great Wall, imperial palaces, tea, regional cuisines and vast modern cities.", "Cultural relics made before 1949 need an export seal, and those older than 1911 generally cannot leave the country.", [
    ["tea", "drink", "mid", "adults", "drinks tradition", "Chinese tea", "Longjing green tea or aged pu'er from a tea merchant.", { soft: true }],
    ["silk-scarf", "clothing", "mid", "adults", "fashion crafts", "Silk scarf", "Silk from Hangzhou or Suzhou, the historic silk cities."],
    ["calligraphy-set", "art", "mid", "teens+", "art crafts tradition", "Calligraphy set", "Brush, ink stick, ink stone and paper: the 'four treasures of the study'."],
    ["chopsticks", "decor", "budget", "all", "cooking home-decor", "Chopsticks", "A boxed pair in lacquered wood or bamboo."],
    ["porcelain", "decor", "premium", "adults", "home-decor crafts art", "Jingdezhen porcelain", "From the town that has made imperial porcelain for a thousand years."],
    ["panda", "toy", "budget", "child", "toys nature", "Plush panda", "Best bought in Chengdu, home of the panda research base."],
    ["paper-cutting", "art", "budget", "all", "art crafts tradition", "Paper cutting", "Intricate red paper designs used as lucky decorations."],
    ["name-seal", "craft", "mid", "teens+", "crafts tradition art", "Carved name seal", "A stone stamp with your name carved in Chinese characters while you wait."],
  ]),
  country("IN", "The Taj Mahal, spices, yoga, festivals and Bollywood.", "Antiques over 100 years old cannot be exported, and shahtoosh shawls and ivory are illegal.", [
    ["tea", "drink", "budget", "adults", "drinks", "Darjeeling or Assam tea", "Loose-leaf tea straight from the growing regions.", { soft: true }],
    ["spice-box", "food", "budget", "adults", "cooking food", "Masala dabba", "A round steel tin with seven spices, as used in Indian kitchens."],
    ["pashmina", "clothing", "premium", "adults", "fashion crafts", "Pashmina shawl", "Fine Kashmiri wool; genuine pieces are costly and often certified."],
    ["block-print", "decor", "mid", "adults", "home-decor crafts fashion", "Block-printed textile", "Cotton printed by hand with carved wooden blocks in Rajasthan.", { region: "Rajasthan" }],
    ["bangles", "jewelry", "budget", "teens+", "jewelry fashion tradition", "Glass bangles", "Sold by the dozen in every colour."],
    ["diya", "decor", "budget", "adults", "tradition home-decor", "Brass diya", "An oil lamp lit for Diwali, the festival of lights.", { months: [10, 11] }],
    ["madhubani", "art", "mid", "adults", "art tradition", "Madhubani painting", "Folk painting from Bihar with dense patterns and natural dyes."],
    ["cricket-jersey", "clothing", "mid", "all", "sports", "India cricket jersey", "The blue shirt of the national team."],
  ]),
  country("TH", "Temples, street food, islands and Thai massage.", "Buddha images and antiques need an export licence, and using Buddha images as decoration is considered disrespectful.", [
    ["silk-scarf", "clothing", "mid", "adults", "fashion crafts", "Thai silk scarf", "Handwoven silk with a characteristic slubbed texture."],
    ["curry-paste", "food", "budget", "adults", "cooking food", "Curry paste", "Green, red and massaman pastes in vacuum packs."],
    ["elephant-trousers", "clothing", "budget", "teens+", "fashion humor", "Elephant trousers", "The loose printed trousers every backpacker ends up owning."],
    ["celadon", "decor", "mid", "adults", "home-decor crafts", "Celadon ceramics", "Jade-green crackle-glazed pottery from Chiang Mai."],
    ["herbal-balm", "cosmetics", "budget", "adults", "beauty", "Herbal balm and inhaler", "Menthol balm and pocket inhalers sold in every pharmacy."],
    ["dried-mango", "food", "budget", "all", "sweets", "Dried mango", "Soft dried fruit, easy to carry and share."],
    ["spa-set", "cosmetics", "mid", "adults", "beauty", "Lemongrass spa set", "Soaps, oils and herbal compress balls."],
    ["muay-thai-shorts", "clothing", "budget", "teens+", "sports", "Muay Thai shorts", "Satin shorts of the national martial art."],
  ]),
  country("VN", "Street food, Ha Long Bay, rice terraces and streets full of motorbikes.", "Antiques may not be exported without a permit; keep receipts for anything that looks old.", [
    ["coffee", "drink", "budget", "adults", "drinks cooking", "Coffee with a phin filter", "Robusta beans and the small metal drip filter used to brew them.", { soft: true }],
    ["conical-hat", "clothing", "budget", "all", "tradition fashion", "Nón lá", "The conical palm-leaf hat."],
    ["lacquerware", "decor", "mid", "adults", "home-decor crafts art", "Lacquerware", "Boxes and trays with eggshell or mother-of-pearl inlay."],
    ["ao-dai", "clothing", "premium", "adults", "fashion tradition", "Tailor-made áo dài", "Hoi An tailors make the national dress to measure within a day."],
    ["silk-lantern", "decor", "budget", "all", "home-decor crafts", "Silk lantern", "Folding lanterns from Hoi An's old town."],
    ["lotus-tea", "drink", "budget", "adults", "drinks", "Lotus tea", "Green tea scented with lotus flowers.", { soft: true }],
    ["water-puppet", "toy", "budget", "kids", "toys tradition crafts", "Water puppet", "A lacquered wooden puppet from a northern folk art."],
  ]),
  country("ID", "Bali, volcanoes, rainforest, batik and thousands of islands.", "Products made from turtle shell, coral and other protected wildlife are illegal to export.", [
    ["batik", "clothing", "mid", "adults", "fashion crafts tradition", "Batik", "Wax-resist dyed cloth; hand-drawn batik tulis is the finest.", { region: "Java" }],
    ["wayang", "craft", "mid", "adults", "art tradition crafts", "Wayang puppet", "A leather shadow puppet from Javanese theatre.", { region: "Java" }],
    ["coffee", "drink", "mid", "adults", "drinks", "Indonesian coffee", "Beans from Sumatra, Java or Toraja.", { soft: true }],
    ["wood-carving", "decor", "mid", "adults", "art home-decor crafts", "Balinese wood carving", "From the carving villages around Ubud.", { region: "Bali" }],
    ["silver", "jewelry", "mid", "adults", "jewelry crafts", "Balinese silver", "Granulated silverwork from the village of Celuk.", { region: "Bali" }],
    ["sambal", "food", "budget", "adults", "cooking food", "Sambal", "Chilli paste in countless regional versions."],
    ["angklung", "music", "budget", "kids", "music tradition", "Angklung", "A bamboo instrument played by shaking."],
  ]),
  country("MY", "The Petronas Towers, rainforest, street food and a mix of Malay, Chinese and Indian cultures.", "Durian is banned on public transport and in most hotels because of its smell.", [
    ["pewter", "decor", "premium", "adults", "home-decor crafts collectibles", "Pewter ware", "Malaysia was the world's tin capital; pewter is the classic gift."],
    ["batik", "clothing", "mid", "adults", "fashion crafts", "Malaysian batik", "Hand-painted with large floral motifs."],
    ["white-coffee", "drink", "budget", "adults", "drinks", "Ipoh white coffee", "Beans roasted with margarine for a smooth taste.", { soft: true }],
    ["highland-tea", "drink", "budget", "adults", "drinks", "Cameron Highlands tea", "Black tea from hill plantations.", { soft: true }],
    ["kaya", "food", "budget", "all", "sweets food", "Kaya", "Coconut and pandan jam eaten on toast."],
    ["wau-kite", "decor", "mid", "all", "tradition crafts", "Wau kite", "A decorated moon-kite from the east coast."],
  ]),
  country("SG", "A garden city-state with hawker food, strict laws and a futuristic skyline.", "Chewing gum is not sold, and littering or eating on the metro brings heavy fines.", [
    ["kaya", "food", "budget", "all", "sweets", "Kaya jam", "The coconut jam of the traditional breakfast set."],
    ["sling-mix", "drink", "mid", "adults", "drinks", "Singapore Sling", "A bottled version of the cocktail created at a colonial-era hotel."],
    ["orchid-jewelry", "jewelry", "mid", "adults", "jewelry nature", "Orchid jewellery", "Real orchids preserved and plated in gold."],
    ["tea", "drink", "mid", "adults", "drinks", "Luxury tea blend", "Tins from the city's well-known tea houses.", { soft: true }],
    ["merlion", "decor", "budget", "all", "collectibles humor", "Merlion figurine", "The lion-headed fish that is the city's mascot."],
    ["peranakan", "decor", "mid", "adults", "home-decor crafts tradition", "Peranakan tiles and porcelain", "Pastel patterns of the Straits Chinese heritage."],
  ]),
  country("KR", "K-pop, skincare, kimchi, palaces and technology.", "Many shops refund tax to tourists on the spot on showing a passport.", [
    ["skincare", "cosmetics", "budget", "teens+", "beauty", "Sheet masks and skincare", "Sold in bundles at very low prices."],
    ["kpop-album", "music", "mid", "teens+", "music collectibles", "K-pop album", "Physical albums come with photocards and posters."],
    ["gim", "food", "budget", "all", "food", "Roasted seaweed", "Crisp salted laver in snack packs."],
    ["soju", "drink", "budget", "adults", "drinks", "Soju", "The clear spirit in green bottles, in many fruit flavours."],
    ["bojagi", "craft", "mid", "adults", "crafts tradition", "Bojagi", "A patchwork wrapping cloth."],
    ["red-ginseng", "food", "premium", "adults", "food tradition", "Red ginseng", "Sold as extract, tea or sweets; a prestigious gift."],
    ["chopsticks-set", "decor", "budget", "all", "cooking home-decor", "Metal chopsticks and spoon", "Korea is unusual in using flat metal chopsticks."],
    ["character-plush", "toy", "budget", "kids", "toys collectibles", "Character plush", "From the flagship stores of Korea's messaging-app mascots."],
  ]),
  country("PH", "More than 7,000 islands, beaches, jeepneys and karaoke.", "Shells, corals and anything from sea turtles are protected and cannot be taken out.", [
    ["dried-mango", "food", "budget", "all", "sweets", "Dried mangoes", "Cebu's are the best known."],
    ["barong", "clothing", "premium", "adults", "fashion tradition", "Barong Tagalog", "The embroidered formal shirt of sheer pineapple or banana fibre."],
    ["parol", "decor", "mid", "adults", "home-decor crafts", "Capiz parol", "A star-shaped Christmas lantern of translucent shell.", { months: [11, 12] }],
    ["jeepney", "toy", "budget", "kids", "toys collectibles", "Miniature jeepney", "A model of the decorated minibuses."],
    ["ube-jam", "food", "budget", "all", "sweets", "Ube jam", "Purple yam jam from the hill town of Baguio."],
    ["abaca-bag", "accessory", "mid", "adults", "fashion crafts", "Abaca bag", "Woven from Manila hemp."],
  ]),
  country("AE", "Skyscrapers, desert, gold souks and luxury shopping.", "Tourists can reclaim VAT at the airport; drinking outside licensed venues can lead to fines.", [
    ["dates", "food", "mid", "all", "sweets food", "Stuffed dates", "Filled with nuts or candied orange, in gift boxes."],
    ["oud", "cosmetics", "premium", "adults", "beauty", "Oud perfume", "Rich wood-based scents and perfume oils."],
    ["gold", "jewelry", "premium", "adults", "jewelry", "Gold from the souk", "Sold by weight at the day's price plus a making charge."],
    ["dallah", "decor", "mid", "adults", "home-decor tradition drinks", "Dallah", "The long-spouted Arabic coffee pot, a symbol of hospitality."],
    ["camel-milk-chocolate", "food", "mid", "all", "sweets", "Camel-milk chocolate", "A local novelty made in Dubai."],
    ["spices", "food", "budget", "adults", "cooking", "Spice souk selection", "Saffron, dried limes and spice blends."],
  ]),
  country("IL", "Jerusalem's holy sites, the Dead Sea, Tel Aviv and high-tech.", "Check your government's travel advice; antiquities may be bought only from licensed dealers and need an export permit.", [
    ["dead-sea", "cosmetics", "mid", "adults", "beauty", "Dead Sea cosmetics", "Mud masks and bath salts rich in minerals."],
    ["halva", "food", "budget", "all", "sweets", "Halva", "Sesame sweet sold by the slice in the markets."],
    ["olive-wood", "craft", "mid", "adults", "crafts tradition", "Olive-wood carving", "Bowls and figures carved from pruned branches."],
    ["hamsa", "jewelry", "budget", "all", "jewelry tradition", "Hamsa charm", "The hand-shaped amulet against the evil eye."],
    ["zaatar", "food", "budget", "adults", "cooking food", "Za'atar", "A herb, sesame and sumac blend."],
    ["armenian-ceramics", "decor", "mid", "adults", "home-decor crafts art", "Armenian ceramics", "Hand-painted tiles and bowls from Jerusalem's Old City."],
  ]),
  country("JO", "Petra, the Wadi Rum desert and the Dead Sea.", "Do not buy 'ancient' coins or artefacts offered at sites: they are either fakes or illegal to export.", [
    ["sand-bottle", "art", "budget", "all", "art crafts", "Sand art bottle", "Desert scenes built up from coloured sand, made while you watch."],
    ["dead-sea", "cosmetics", "mid", "adults", "beauty", "Dead Sea products", "Mud and salt cosmetics from the lowest point on Earth."],
    ["shemagh", "clothing", "budget", "teens+", "fashion tradition", "Shemagh", "The red-and-white checked headscarf."],
    ["mosaic", "art", "mid", "adults", "art crafts history", "Madaba mosaic", "Stone mosaics from the town of Byzantine mosaics."],
    ["zaatar", "food", "budget", "adults", "cooking food", "Za'atar", "Thyme and sesame blend eaten with bread and olive oil."],
    ["bedouin-silver", "jewelry", "mid", "adults", "jewelry crafts tradition", "Bedouin silver", "Jewellery from women's cooperatives."],
  ]),
  country("AF", "The Hindu Kush, lapis lazuli and a long history at the crossroads of Asia.", "Most governments advise against all travel.", [
    ["lapis", "jewelry", "mid", "adults", "jewelry nature", "Lapis lazuli", "The deep blue stone mined in Badakhshan for thousands of years."],
    ["carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Afghan carpet", "Hand-knotted wool carpets in deep reds."],
    ["pakol", "clothing", "budget", "adults", "tradition fashion", "Pakol", "A soft rolled wool hat."],
    ["saffron", "food", "mid", "adults", "cooking food", "Herat saffron", "Regularly rated among the best in the world."],
  ]),
  country("AM", "Ancient monasteries, views of Mount Ararat, brandy and apricots.", "The land borders with Turkey and Azerbaijan are closed.", [
    ["brandy", "drink", "mid", "adults", "drinks", "Armenian brandy", "Aged grape brandy with a long reputation."],
    ["duduk", "music", "mid", "adults", "music tradition crafts", "Duduk", "A double-reed flute of apricot wood with a mournful sound."],
    ["pomegranate", "decor", "budget", "all", "tradition home-decor crafts", "Ceramic pomegranate", "The national symbol of fertility and good fortune."],
    ["dried-fruit", "food", "budget", "all", "sweets food", "Dried apricots and sujukh", "Sun-dried fruit and walnuts strung in grape syrup."],
    ["khachkar", "craft", "mid", "adults", "crafts history art", "Miniature khachkar", "A small carved cross-stone."],
  ]),
  country("AZ", "The Caspian shore, the Flame Towers, carpets and tea culture.", "Carpets and antiques need an export certificate, which reputable sellers arrange.", [
    ["carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Azerbaijani carpet", "Its weaving tradition is on UNESCO's heritage list."],
    ["armudu", "decor", "budget", "adults", "drinks home-decor tradition", "Armudu glasses", "Pear-shaped tea glasses."],
    ["pakhlava", "food", "budget", "all", "sweets", "Baku pakhlava", "Diamond-shaped pastry with nuts and saffron."],
    ["kelaghayi", "clothing", "mid", "adults", "fashion tradition crafts", "Kelaghayi", "A block-printed silk headscarf."],
    ["narsharab", "food", "budget", "adults", "cooking", "Narsharab", "Thick pomegranate sauce for fish and meat."],
  ]),
  country("BH", "Pearl-diving heritage, Formula 1 and ancient burial mounds.", "Only natural pearls may be traded: cultured pearls are banned from sale.", [
    ["pearls", "jewelry", "premium", "adults", "jewelry", "Natural pearls", "Bahrain's pearls come with a certificate of authenticity."],
    ["halwa", "food", "budget", "all", "sweets", "Bahraini halwa", "A jelly-like sweet with saffron and nuts."],
    ["pottery", "decor", "budget", "adults", "home-decor crafts", "A'ali pottery", "Made in a village of traditional kilns."],
    ["palm-basket", "craft", "budget", "adults", "crafts home-decor", "Palm-leaf basket", "Woven in the village of Karbabad."],
  ]),
  country("BD", "River deltas, the Sundarbans mangroves, tea gardens and textiles.", "Bargaining is expected in markets; fixed-price craft shops are easier for gifts.", [
    ["jamdani", "clothing", "premium", "adults", "fashion crafts tradition", "Jamdani", "Fine handwoven muslin with woven-in motifs."],
    ["nakshi-kantha", "decor", "mid", "adults", "home-decor crafts tradition", "Nakshi kantha", "A quilt embroidered with scenes of village life."],
    ["jute-bag", "accessory", "budget", "adults", "fashion crafts nature", "Jute bag", "Made from the 'golden fibre' of Bengal."],
    ["tea", "drink", "budget", "adults", "drinks", "Sylhet tea", "Black tea from the north-eastern hills.", { soft: true }],
    ["rickshaw-art", "art", "budget", "all", "art humor", "Rickshaw art", "Painted panels in the exuberant style of Dhaka's rickshaws."],
  ]),
  country("BT", "Himalayan monasteries and the idea of Gross National Happiness.", "Visitors pay a daily Sustainable Development Fee, and antiques and old religious objects cannot be exported.", [
    ["textile", "clothing", "premium", "adults", "fashion crafts tradition", "Handwoven textile", "Intricate cloth woven on backstrap looms."],
    ["stamps", "art", "budget", "adults", "collectibles", "Bhutanese stamps", "Famous for unusual issues, including ones that play music."],
    ["prayer-flags", "decor", "budget", "all", "tradition home-decor", "Prayer flags", "Five colours printed with mantras."],
    ["thangka", "art", "premium", "adults", "art tradition", "Thangka", "A Buddhist scroll painting; buy new work with a receipt."],
    ["incense", "cosmetics", "budget", "adults", "tradition beauty", "Handmade incense", "Rolled from Himalayan herbs."],
  ]),
  country("BN", "A small oil-rich sultanate with golden-domed mosques and rainforest.", "Alcohol is not sold; non-Muslim visitors may bring in a limited amount for their own use.", [
    ["songket", "clothing", "premium", "adults", "fashion crafts tradition", "Songket", "Brocade woven with gold thread."],
    ["brassware", "decor", "mid", "adults", "home-decor crafts", "Brassware", "Cast brass gongs and kettles."],
    ["woven-basket", "craft", "budget", "adults", "crafts", "Woven basket", "Rattan and pandanus baskets."],
    ["keropok", "food", "budget", "all", "food", "Keropok", "Prawn and fish crackers."],
  ]),
  country("KH", "Angkor Wat, Khmer cuisine and a tragic twentieth-century history.", "Never buy antiquities or carved stone fragments: trade in Angkorian artefacts is illegal.", [
    ["krama", "clothing", "budget", "all", "fashion tradition", "Krama", "The checked cotton scarf Cambodians use for everything."],
    ["kampot-pepper", "food", "mid", "adults", "cooking food", "Kampot pepper", "Protected-origin pepper prized by chefs."],
    ["silk", "clothing", "mid", "adults", "fashion crafts", "Khmer silk", "Handwoven golden silk and ikat."],
    ["palm-sugar", "food", "budget", "all", "sweets cooking", "Palm sugar", "Discs of caramel-flavoured sugar from sugar palms."],
    ["apsara-replica", "art", "mid", "adults", "art history", "Apsara carving replica", "New carvings from artisan workshops in Siem Reap."],
  ]),
  country("GE", "Wine made in clay jars, mountain villages and legendary hospitality.", "Icons, old carpets and antiques need an export permit.", [
    ["qvevri-wine", "drink", "mid", "adults", "drinks tradition", "Qvevri wine", "Amber wine fermented in buried clay vessels."],
    ["churchkhela", "food", "budget", "all", "sweets", "Churchkhela", "Walnuts on a string dipped in thickened grape juice."],
    ["spices", "food", "budget", "adults", "cooking food", "Khmeli suneli and Svan salt", "The spice blends behind Georgian cooking."],
    ["minankari", "jewelry", "mid", "adults", "jewelry crafts art", "Minankari", "Cloisonné enamel jewellery."],
    ["kantsi", "craft", "mid", "adults", "tradition drinks crafts", "Kantsi", "A drinking horn used for toasts."],
  ]),
  country("IR", "Persian gardens, the mosques of Isfahan, poetry and carpets.", "Foreign bank cards do not work, so bring cash; many governments advise against travel.", [
    ["carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Persian carpet", "Hand-knotted, with styles named after their cities."],
    ["saffron", "food", "mid", "adults", "cooking food", "Saffron", "Iran grows most of the world's supply."],
    ["pistachios", "food", "mid", "all", "food", "Pistachios", "Large, intensely flavoured nuts."],
    ["khatam", "craft", "mid", "adults", "crafts art home-decor", "Khatam box", "Marquetry of tiny wood, bone and metal pieces."],
    ["gaz", "food", "budget", "all", "sweets", "Gaz", "Nougat with pistachios from Isfahan."],
  ]),
  country("IQ", "The cradle of Mesopotamian civilisation, between the Tigris and the Euphrates.", "Many governments advise against travel; removing any archaeological object is a serious crime.", [
    ["dates", "food", "budget", "all", "sweets food", "Dates", "Iraq grows hundreds of varieties."],
    ["mann-al-sama", "food", "budget", "all", "sweets", "Mann al-sama", "Nougat with cardamom and pistachios."],
    ["copperware", "decor", "mid", "adults", "home-decor crafts", "Copperware", "Hammered trays and coffee pots from the coppersmiths' market."],
    ["kurdish-rug", "decor", "mid", "adults", "crafts tradition", "Kurdish woven rug", "Flat-woven wool with bold geometric designs."],
  ]),
  country("KZ", "The steppe, nomadic heritage, the Baikonur spaceport and futuristic Astana.", "Distances are enormous; internal flights or overnight trains link the main cities.", [
    ["felt", "decor", "mid", "adults", "home-decor crafts tradition", "Felt slippers or rug", "Felt-making is the classic craft of the steppe."],
    ["chocolate", "food", "budget", "all", "sweets", "Kazakh chocolate", "The bar with the national flag on its wrapper."],
    ["dombra", "music", "premium", "adults", "music tradition", "Dombra", "A two-stringed lute."],
    ["kurt", "food", "budget", "adults", "food", "Kurt", "Hard, salty balls of dried cheese that keep for months."],
    ["yurt-miniature", "decor", "budget", "all", "tradition collectibles", "Miniature yurt", "A felt model of the nomadic tent."],
  ]),
  country("KW", "Oil wealth, the Kuwait Towers and traditional dhow harbours.", "Alcohol is completely banned.", [
    ["dhow", "decor", "mid", "adults", "history collectibles home-decor", "Model dhow", "A wooden model of the pearling boats."],
    ["sadu", "decor", "mid", "adults", "crafts tradition home-decor", "Sadu weaving", "Geometric Bedouin weaving in red and black."],
    ["bukhoor", "cosmetics", "mid", "adults", "beauty", "Perfume oil and bukhoor", "Scented wood chips burned to perfume the home."],
    ["dates", "food", "budget", "all", "sweets", "Dates", "Boxed with nuts and chocolate."],
  ]),
  country("KG", "High mountain lakes, yurts and nomadic horse culture.", "Much of the country lies above 1,500 m, and mountain passes can close from October to May.", [
    ["shyrdak", "decor", "premium", "adults", "home-decor crafts tradition", "Shyrdak", "A felt rug of stitched mirror-image patterns."],
    ["kalpak", "clothing", "budget", "adults", "tradition fashion", "Ak-kalpak", "The tall white felt hat."],
    ["honey", "food", "budget", "all", "food nature", "White mountain honey", "Pale honey from high-altitude sainfoin."],
    ["komuz", "music", "mid", "adults", "music tradition", "Komuz", "A three-stringed lute of apricot wood."],
    ["felt-animals", "toy", "budget", "child", "toys crafts", "Felt animals", "Hand-felted toys made by women's cooperatives."],
  ]),
  country("LA", "The temples of Luang Prabang, the Mekong and slow travel.", "Buddha images and antiques may not be exported.", [
    ["silk", "clothing", "mid", "adults", "fashion crafts tradition", "Handwoven silk", "Scarves with intricate supplementary-weft patterns."],
    ["coffee", "drink", "budget", "adults", "drinks", "Bolaven coffee", "Grown on the volcanic plateau in the south.", { soft: true }],
    ["saa-paper", "craft", "budget", "all", "crafts art", "Saa paper", "Mulberry-bark paper notebooks and lanterns."],
    ["rice-basket", "decor", "budget", "adults", "cooking tradition crafts", "Sticky-rice basket", "The woven container sticky rice is served in."],
  ]),
  country("LB", "Cuisine, cedar trees, the Roman ruins of Baalbek and Beirut's nightlife.", "Check your government's travel advice; the economy runs largely on cash US dollars.", [
    ["baklava", "food", "mid", "all", "sweets", "Lebanese baklava", "Small, less syrupy pastries in a gift tin."],
    ["arak", "drink", "mid", "adults", "drinks", "Arak", "Aniseed spirit served with mezze."],
    ["soap", "cosmetics", "budget", "adults", "beauty tradition", "Tripoli soap", "Olive-oil soap from the old soap khan."],
    ["cedar-carving", "craft", "budget", "adults", "crafts nature", "Cedar-wood carving", "The tree on the flag, carved from pruned wood."],
    ["zaatar", "food", "budget", "adults", "cooking", "Za'atar", "Wild thyme blend from the mountains."],
  ]),
  country("MV", "Overwater villas, coral atolls and diving.", "Exporting coral, shells, sand and turtle products is prohibited; alcohol is available only on resort islands.", [
    ["lacquer-box", "decor", "mid", "adults", "crafts home-decor", "Lacquered box", "Turned wood lacquered in red, black and yellow."],
    ["woven-mat", "decor", "mid", "adults", "crafts tradition", "Thundu kunaa", "A fine reed mat from the southern atolls."],
    ["coconut-oil", "cosmetics", "budget", "adults", "beauty", "Coconut oil", "Cold-pressed on local islands."],
    ["dhoni", "decor", "budget", "all", "collectibles", "Model dhoni", "The traditional Maldivian boat."],
  ]),
  country("MN", "The steppe, nomadic herders, Genghis Khan and the Naadam festival.", "Fossils and antiques cannot be exported; dinosaur fossils are state property.", [
    ["cashmere", "clothing", "premium", "adults", "fashion", "Cashmere", "Mongolia is a leading source; factory shops are far cheaper than abroad."],
    ["felt-slippers", "clothing", "budget", "all", "crafts tradition", "Felt slippers", "Warm slippers of sheep's wool."],
    ["horsehead-fiddle", "decor", "mid", "adults", "music tradition", "Miniature morin khuur", "A small version of the horsehead fiddle."],
    ["shagai", "toy", "budget", "kids", "games tradition", "Shagai", "Ankle bones used for traditional games."],
    ["ger", "decor", "budget", "all", "collectibles", "Miniature ger", "A model of the round felt tent."],
  ]),
  country("MM", "Thousands of temples at Bagan, golden pagodas and Inle Lake.", "Many governments advise against travel; gemstones may be exported only with an official receipt.", [
    ["lacquerware", "decor", "mid", "adults", "home-decor crafts", "Bagan lacquerware", "Bamboo and horsehair bowls with engraved designs."],
    ["longyi", "clothing", "budget", "adults", "fashion tradition", "Longyi", "The wrap skirt worn by men and women."],
    ["thanaka", "cosmetics", "budget", "adults", "beauty tradition", "Thanaka", "A bark paste used as sunscreen and make-up."],
    ["marionette", "toy", "mid", "kids", "toys crafts tradition", "String marionette", "From the puppet theatres of Mandalay."],
    ["pickled-tea", "food", "budget", "adults", "food", "Lahpet", "Pickled tea leaves with crunchy beans and nuts."],
  ]),
  country("NP", "Mount Everest, trekking, temples and prayer flags.", "Objects more than 100 years old cannot be exported; anything that looks old needs a certificate.", [
    ["singing-bowl", "decor", "mid", "adults", "music tradition home-decor", "Singing bowl", "A metal bowl that hums when the rim is rubbed."],
    ["prayer-flags", "decor", "budget", "all", "tradition", "Prayer flags", "Strings of five-coloured flags."],
    ["pashmina", "clothing", "mid", "adults", "fashion", "Pashmina", "Soft Himalayan goat-wool shawls."],
    ["thangka", "art", "premium", "adults", "art tradition", "Thangka", "Scroll paintings from the workshops of Bhaktapur and Boudha."],
    ["tea", "drink", "budget", "adults", "drinks", "Ilam tea", "From gardens just across the border from Darjeeling.", { soft: true }],
    ["lokta-paper", "craft", "budget", "all", "crafts art", "Lokta paper", "Handmade paper notebooks and lampshades."],
  ]),
  country("KP", "A closed one-party state with mass parades, monuments and tightly guided tours.", "Visits are possible only on organised tours with state guides; printed material bought there may be confiscated by customs elsewhere, and some countries bar their citizens from going.", [
    ["propaganda-poster", "art", "mid", "adults", "art history collectibles", "Hand-painted poster", "Propaganda art sold in state shops and studios."],
    ["newspaper", "book", "budget", "adults", "history collectibles", "State newspaper", "A copy of Rodong Sinmun or the English-language Pyongyang Times; never fold or discard a page showing the leaders while there."],
    ["stamps", "art", "budget", "adults", "collectibles history", "Postage stamps", "Sold in albums at the stamp shop in Pyongyang."],
    ["magazines", "book", "budget", "adults", "history collectibles books", "Foreign-language magazines", "Official magazines and booklets printed for visitors."],
    ["ginseng", "food", "mid", "adults", "food tradition", "Kaesong ginseng", "The country's best-known export product."],
  ]),
  country("OM", "Frankincense, forts, deserts and the fjord-like coast of Musandam.", "The khanjar is a dagger: it must travel in checked luggage and may be restricted in your home country.", [
    ["frankincense", "cosmetics", "budget", "adults", "beauty tradition", "Frankincense", "Resin from Dhofar, with a clay burner."],
    ["khanjar", "decor", "premium", "adults", "tradition collectibles", "Khanjar", "The curved ceremonial dagger on the national emblem, usually sold framed."],
    ["halwa", "food", "budget", "all", "sweets", "Omani halwa", "A sticky sweet with rosewater and saffron."],
    ["kumma", "clothing", "budget", "adults", "tradition fashion", "Kumma", "An embroidered cap."],
    ["silver", "jewelry", "mid", "adults", "jewelry crafts", "Bedouin silver", "From the souk at Nizwa."],
  ]),
  country("PK", "The Karakoram mountains, Mughal monuments, truck art and cricket.", "Antiques cannot be exported without a permit.", [
    ["truck-art", "art", "budget", "all", "art humor home-decor", "Truck art", "Kettles, trays and frames painted like Pakistan's lorries."],
    ["shawl", "clothing", "mid", "adults", "fashion", "Wool shawl", "Fine shawls from Kashmir and the northern valleys."],
    ["salt-lamp", "decor", "budget", "adults", "home-decor nature", "Rock-salt lamp", "Carved from pink salt of the Khewra mine."],
    ["onyx", "decor", "mid", "adults", "home-decor crafts", "Onyx carving", "Vases and chess sets in green onyx."],
    ["ajrak", "clothing", "mid", "adults", "fashion tradition crafts", "Ajrak", "Indigo and crimson block-printed cloth from Sindh."],
  ]),
  country("QA", "Futuristic Doha, the Museum of Islamic Art and desert dunes.", "Alcohol is served only in licensed hotels and cannot be brought into the country.", [
    ["oud", "cosmetics", "premium", "adults", "beauty", "Oud and bukhoor", "Perfume oils and incense from the souq."],
    ["dates", "food", "budget", "all", "sweets", "Dates", "Stuffed and chocolate-coated."],
    ["dhow", "decor", "mid", "adults", "collectibles", "Model dhow", "The boats once used for pearling."],
    ["falcon-hood", "craft", "mid", "adults", "tradition collectibles", "Falconry hood", "A stitched leather hood from the falcon souq."],
    ["spices", "food", "budget", "adults", "cooking", "Souq spices", "Saffron, dried limes and blends."],
  ]),
  country("SA", "Mecca and Medina, desert landscapes and the rock tombs of Hegra.", "Alcohol is banned; Mecca and the centre of Medina are open to Muslims only.", [
    ["dates", "food", "mid", "all", "sweets food", "Ajwa dates", "Dark soft dates from Medina."],
    ["oud", "cosmetics", "premium", "adults", "beauty", "Oud", "Wood chips and perfume oil."],
    ["saudi-coffee", "drink", "budget", "adults", "drinks tradition", "Saudi coffee", "Lightly roasted beans with cardamom.", { soft: true }],
    ["prayer-beads", "accessory", "budget", "adults", "tradition", "Prayer beads", "A misbaha of wood, stone or amber."],
    ["shemagh", "clothing", "budget", "adults", "tradition fashion", "Shemagh", "The red-checked headscarf."],
  ]),
  country("LK", "Tea plantations, beaches, elephants and ancient Buddhist cities.", "Antiques over 50 years old, ivory and coral cannot be exported.", [
    ["tea", "drink", "budget", "adults", "drinks", "Ceylon tea", "From hill estates, graded by leaf size.", { soft: true }],
    ["cinnamon", "food", "budget", "adults", "cooking food", "Ceylon cinnamon", "True cinnamon, in soft layered quills."],
    ["sapphire", "jewelry", "premium", "adults", "jewelry", "Ceylon sapphire", "Buy only from shops that issue a certificate."],
    ["mask", "decor", "mid", "adults", "art tradition crafts", "Carved mask", "Painted masks from the southern coast."],
    ["batik", "clothing", "mid", "adults", "fashion crafts", "Batik", "Wall hangings and sarongs."],
    ["ayurveda", "cosmetics", "budget", "adults", "beauty", "Ayurvedic balms and oils", "Herbal remedies from spice gardens."],
  ]),
  country("SY", "Damascus and Aleppo, among the oldest continuously inhabited cities, and their souks.", "Most governments advise against all travel.", [
    ["aleppo-soap", "cosmetics", "budget", "adults", "beauty tradition", "Aleppo soap", "Olive and laurel oil soap, aged for months."],
    ["brocade", "clothing", "premium", "adults", "fashion crafts", "Damascus brocade", "Silk woven with gold and silver thread."],
    ["inlaid-box", "craft", "mid", "adults", "crafts home-decor", "Inlaid box", "Walnut wood with mother-of-pearl marquetry."],
    ["sweets", "food", "mid", "all", "sweets", "Damascene sweets", "Pistachio pastries and candied fruit."],
  ]),
  country("TJ", "The Pamir Highway and some of the highest mountains in Central Asia.", "A special permit is needed for the Gorno-Badakhshan region.", [
    ["suzani", "decor", "mid", "adults", "home-decor crafts tradition", "Suzani", "A large embroidered hanging."],
    ["skullcap", "clothing", "budget", "adults", "tradition fashion", "Embroidered skullcap", "The square toqi."],
    ["jurabs", "clothing", "budget", "all", "crafts tradition", "Pamiri socks", "Thick, brightly patterned knitted socks."],
    ["dried-fruit", "food", "budget", "all", "sweets food", "Dried fruit", "Apricots, mulberries and nuts."],
  ]),
  country("TL", "Coral reefs, mountain coffee and one of Asia's youngest nations.", "The US dollar is the official currency.", [
    ["tais", "clothing", "mid", "adults", "fashion crafts tradition", "Tais", "Handwoven cloth with patterns that identify each district."],
    ["coffee", "drink", "budget", "adults", "drinks", "Timorese coffee", "Organic arabica from the highlands.", { soft: true }],
    ["basket", "craft", "budget", "adults", "crafts", "Palm basket", "Woven from lontar palm leaves."],
    ["carving", "decor", "mid", "adults", "art crafts", "Ataúro carving", "Wooden figures from Ataúro island."],
  ]),
  country("TM", "The Karakum desert, the burning Darvaza gas crater and marble-white Ashgabat.", "Carpets need an export certificate, and independent travel is heavily restricted.", [
    ["carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Turkmen carpet", "Deep red, with the repeating gul motif."],
    ["telpek", "clothing", "mid", "adults", "tradition fashion", "Telpek", "A shaggy sheepskin hat."],
    ["silver-jewelry", "jewelry", "mid", "adults", "jewelry tradition", "Turkmen silver", "Heavy silver set with carnelian."],
    ["dried-melon", "food", "budget", "all", "sweets", "Dried melon", "Plaited strips of the country's famous melons."],
  ]),
  country("UZ", "The Silk Road cities of Samarkand, Bukhara and Khiva.", "Items over 50 years old need an export certificate; keep receipts for ceramics and carpets.", [
    ["suzani", "decor", "mid", "adults", "home-decor crafts tradition", "Suzani", "Embroidery with suns, moons and pomegranates."],
    ["rishtan-ceramics", "decor", "mid", "adults", "home-decor crafts art", "Rishtan ceramics", "Turquoise and cobalt glazed plates."],
    ["ikat", "clothing", "mid", "adults", "fashion crafts", "Ikat silk", "Cloud-patterned cloth from the Fergana Valley."],
    ["miniature", "art", "mid", "adults", "art history", "Miniature painting", "Scenes painted on silk paper or lacquer boxes."],
    ["doppi", "clothing", "budget", "all", "tradition", "Doppi", "A four-sided embroidered cap."],
    ["dried-fruit", "food", "budget", "all", "sweets", "Dried fruit and nuts", "From the bazaar in Samarkand."],
  ]),
  country("YE", "Mud-brick tower cities, Socotra's dragon-blood trees and the home of mocha coffee.", "Most governments advise against all travel.", [
    ["coffee", "drink", "mid", "adults", "drinks", "Mocha coffee", "Named after the Yemeni port that first shipped it.", { soft: true }],
    ["sidr-honey", "food", "premium", "adults", "food nature", "Sidr honey", "Among the most prized honeys in the world."],
    ["silver", "jewelry", "mid", "adults", "jewelry crafts", "Yemeni silver", "Fine filigree and granulation work."],
    ["frankincense", "cosmetics", "budget", "adults", "beauty", "Frankincense", "Resin traded from here since antiquity."],
  ]),
  country("PS", "Bethlehem, Jerusalem's Old City, olive groves and embroidery.", "Check your government's travel advice; access depends on checkpoints that can close without notice.", [
    ["olive-wood", "craft", "mid", "adults", "crafts tradition", "Olive-wood carving", "Carved in family workshops in Bethlehem."],
    ["tatreez", "clothing", "mid", "adults", "fashion crafts tradition", "Tatreez", "Cross-stitch embroidery with village patterns."],
    ["hebron-glass", "decor", "mid", "adults", "home-decor crafts", "Hebron glass", "Hand-blown glass in blue and turquoise."],
    ["nablus-soap", "cosmetics", "budget", "adults", "beauty tradition", "Nablus soap", "Olive-oil soap made in the same way for centuries."],
    ["keffiyeh", "clothing", "budget", "teens+", "tradition fashion", "Keffiyeh", "The black-and-white checked scarf."],
  ]),
  country("TW", "Night markets, bubble tea, mountains and semiconductors.", "Pineapple cakes are the standard gift to take home; fresh fruit and meat face strict rules at most borders.", [
    ["pineapple-cake", "food", "budget", "all", "sweets", "Pineapple cakes", "Buttery pastries with pineapple jam, individually wrapped."],
    ["oolong", "drink", "mid", "adults", "drinks", "High-mountain oolong", "Fragrant tea from plantations above 1,000 m.", { soft: true }],
    ["bubble-tea-kit", "food", "budget", "teens+", "sweets drinks", "Bubble tea kit", "Tapioca pearls and tea, from where the drink was invented."],
    ["tea-set", "decor", "mid", "adults", "home-decor drinks crafts", "Ceramic tea set", "From the pottery town of Yingge."],
    ["sky-lantern", "decor", "budget", "all", "tradition collectibles", "Miniature sky lantern", "A keepsake of the lantern festival at Pingxi."],
  ]),
  country("HK", "The harbour skyline, dim sum, trams and street markets.", "There is no sales tax, so there is nothing to reclaim on leaving.", [
    ["egg-rolls", "food", "budget", "all", "sweets", "Egg rolls and almond biscuits", "From long-established local bakeries."],
    ["tea", "drink", "mid", "adults", "drinks", "Chinese tea", "Aged pu'er from a traditional tea merchant.", { soft: true }],
    ["mahjong-set", "accessory", "mid", "adults", "games tradition", "Mahjong set", "A travel-sized set of tiles."],
    ["tailored-shirt", "clothing", "premium", "adults", "fashion", "Tailor-made shirt", "Hong Kong tailors can deliver within a day or two."],
    ["tram-model", "toy", "budget", "kids", "toys collectibles", "Tram or ferry model", "Models of the double-decker tram and the harbour ferry."],
  ]),
  country("MO", "Casinos, Portuguese colonial squares and egg tarts.", "Macau has its own currency, the pataca, but Hong Kong dollars are accepted everywhere.", [
    ["almond-cookies", "food", "budget", "all", "sweets", "Almond cookies", "Crumbly biscuits pressed in wooden moulds."],
    ["phoenix-rolls", "food", "budget", "all", "sweets", "Phoenix egg rolls", "Thin rolled wafers, some filled with seaweed or pork floss."],
    ["tile", "decor", "budget", "adults", "home-decor history", "Portuguese-style tile", "Blue-and-white tiles like the old street signs."],
    ["playing-cards", "accessory", "budget", "adults", "games collectibles", "Casino playing cards", "Used decks sold as souvenirs."],
  ]),
];
