import { country, type CountrySeed } from "../define";

export const europe: CountrySeed[] = [
  country("AT", "Classical music, imperial Vienna, Alpine skiing and coffee-house culture.", "Most shops close on Sundays; buy gifts on Saturday or at the main stations and airport.", [
    ["mozartkugeln", "food", "budget", "all", "sweets food", "Mozartkugeln", "Chocolate balls filled with pistachio marzipan and nougat, created in Salzburg.", { region: "Salzburg" }],
    ["sachertorte", "food", "mid", "all", "sweets", "Sachertorte in a wooden box", "Vienna's chocolate and apricot cake, packed so that it keeps for the journey.", { region: "Vienna" }],
    ["snow-globe", "decor", "budget", "all", "collectibles home-decor", "Viennese snow globe", "The snow globe was invented in Vienna around 1900; the original workshop still makes them.", { region: "Vienna" }],
    ["manner-wafers", "food", "budget", "all", "sweets", "Manner hazelnut wafers", "Pink-wrapped wafers sold since 1898."],
    ["trachten", "clothing", "premium", "teens+", "fashion tradition", "Dirndl or Trachten accessory", "Traditional Alpine dress; a scarf or felt hat is the affordable version."],
    ["pumpkin-seed-oil", "food", "mid", "adults", "cooking food", "Styrian pumpkin seed oil", "Dark green, nutty oil for salads, a protected product of Styria.", { region: "Styria" }],
    ["classical-recording", "music", "budget", "adults", "music history", "Classical recording", "Mozart or Strauss from the shop of an opera house or concert hall."],
    ["marillenschnaps", "drink", "mid", "adults", "drinks", "Marillenschnaps", "Apricot brandy from the Wachau valley."],
  ]),
  country("CH", "The Alps, watchmaking, chocolate and cheese.", "Switzerland is outside the EU customs area: prices are high, and visitors living abroad can claim VAT back on larger purchases.", [
    ["chocolate", "food", "mid", "all", "sweets", "Swiss chocolate", "Bars and pralines from a chocolatier rather than the supermarket classics."],
    ["army-knife", "accessory", "mid", "teens+", "tech crafts collectibles", "Swiss Army knife", "The red pocket knife; it must travel in checked luggage."],
    ["watch", "jewelry", "premium", "adults", "fashion jewelry tech", "Swiss watch", "From affordable plastic models to fine mechanical ones."],
    ["cowbell", "decor", "budget", "all", "tradition home-decor music", "Decorated cowbell", "A small version of the bells worn by cows on Alpine pastures."],
    ["cheese", "food", "mid", "adults", "food cooking", "Gruyère or Appenzeller", "Vacuum-packed hard cheese travels well; check import rules outside Europe."],
    ["fondue-set", "decor", "mid", "adults", "cooking home-decor", "Fondue set", "A caquelon pot with long forks for cheese fondue at home."],
    ["music-box", "decor", "premium", "adults", "music crafts collectibles", "Swiss music box", "Mechanical music boxes are a speciality of the Jura mountains."],
  ]),
  country("NL", "Canals, cycling, tulips, windmills and Golden Age painters.", "Flower bulbs need a plant-health certificate to enter many countries outside the EU; buy only packs that carry one.", [
    ["stroopwafels", "food", "budget", "all", "sweets", "Stroopwafels", "Thin waffles filled with caramel syrup, best warmed over a cup."],
    ["delft-blue", "decor", "mid", "adults", "home-decor art tradition", "Delft Blue pottery", "Hand-painted pieces carry the maker's mark on the base."],
    ["tulip-bulbs", "craft", "budget", "adults", "nature", "Tulip bulbs", "Certified bulbs from the flower market, planted in autumn for spring."],
    ["gouda", "food", "mid", "adults", "food cooking", "Aged Gouda", "Old Gouda is firm and travels well without refrigeration."],
    ["clogs", "decor", "budget", "all", "tradition collectibles humor", "Wooden clogs", "Painted klompen, from full size to keyring."],
    ["miffy", "toy", "mid", "child", "toys books", "Miffy plush", "The little rabbit created by Dutch illustrator Dick Bruna."],
    ["museum-print", "art", "budget", "teens+", "art home-decor", "Museum art print", "A Van Gogh, Vermeer or Rembrandt print from a museum shop."],
    ["jenever", "drink", "mid", "adults", "drinks tradition", "Jenever", "The Dutch juniper spirit from which gin descends."],
  ]),
  country("BE", "Chocolate, beer, waffles, comic strips and medieval town squares.", "Pralines are fresh: buy them at the end of the trip and keep them cool.", [
    ["pralines", "food", "mid", "all", "sweets", "Belgian pralines", "Filled chocolates, boxed to order by a chocolatier."],
    ["trappist-beer", "drink", "mid", "adults", "drinks tradition", "Trappist beer", "Brewed in abbeys and often sold with its matching glass."],
    ["speculoos", "food", "budget", "all", "sweets", "Speculoos biscuits", "Spiced caramelised biscuits, also sold as a spread."],
    ["lace", "craft", "premium", "adults", "crafts tradition home-decor", "Bruges lace", "Handmade bobbin lace; ask for a certificate, as much on sale is machine-made.", { region: "West Flanders" }],
    ["comic-album", "book", "budget", "kids", "books humor art", "Comic album", "Tintin, the Smurfs or Lucky Luke, from the homeland of the comic strip."],
    ["liege-waffles", "food", "budget", "all", "sweets", "Liège waffles", "Dense waffles with pearl sugar, sold packed for travel."],
  ]),
  country("IE", "Green landscapes, pubs, traditional music and literature.", "Ireland is in the EU but outside the Schengen area, so expect passport checks when arriving from the continent.", [
    ["aran-sweater", "clothing", "premium", "teens+", "fashion tradition crafts", "Aran sweater", "Cream wool knit with cable patterns from the Aran Islands."],
    ["whiskey", "drink", "mid", "adults", "drinks", "Irish whiskey", "Triple-distilled and smooth; distilleries sell exclusive bottlings."],
    ["claddagh-ring", "jewelry", "mid", "teens+", "jewelry tradition", "Claddagh ring", "Hands, heart and crown for friendship, love and loyalty; from Galway.", { region: "Galway" }],
    ["tin-whistle", "music", "budget", "kids", "music tradition toys", "Tin whistle", "The simple flute of Irish traditional music, with a tune book."],
    ["breakfast-tea", "drink", "budget", "adults", "drinks", "Irish breakfast tea", "A strong black tea blend drunk with milk.", { soft: true }],
    ["connemara-marble", "jewelry", "budget", "adults", "jewelry nature", "Connemara marble pendant", "Green marble quarried in the west of Ireland."],
    ["tweed-cap", "clothing", "mid", "adults", "fashion tradition", "Donegal tweed cap", "A flat cap in flecked handwoven tweed.", { region: "Donegal" }],
  ]),
  country("SE", "Design, forests and lakes, the fika coffee break and Midsummer.", "Sweden is close to cashless: many shops and cafés accept cards only.", [
    ["dala-horse", "decor", "mid", "all", "tradition crafts collectibles", "Dala horse", "A carved and painted wooden horse from Dalarna.", { region: "Dalarna" }],
    ["salty-liquorice", "food", "budget", "teens+", "sweets", "Salty liquorice", "An acquired taste that Swedes love; fun to share."],
    ["cloudberry-jam", "food", "mid", "adults", "food nature", "Cloudberry jam", "Made from golden berries picked in northern bogs."],
    ["design-textile", "decor", "mid", "adults", "home-decor fashion", "Scandinavian design textile", "A tea towel or cushion cover in a classic Swedish print."],
    ["pippi-book", "book", "budget", "child", "books", "Pippi Longstocking book", "Astrid Lindgren's stories, available in many languages."],
    ["wooden-clogs", "clothing", "mid", "adults", "fashion", "Swedish clogs", "Leather-topped wooden clogs (träskor)."],
    ["glassware", "decor", "premium", "adults", "home-decor art crafts", "Småland glass", "Hand-blown glass from the 'Kingdom of Crystal'.", { region: "Småland" }],
  ]),
  country("NO", "Fjords, the northern lights, the midnight sun and winter sports.", "Alcohol is expensive and, above beer strength, sold only in state Vinmonopolet shops with short opening hours.", [
    ["knitted-sweater", "clothing", "premium", "teens+", "fashion tradition", "Norwegian knitted sweater", "Wool sweater with the traditional patterned yoke."],
    ["brunost", "food", "budget", "all", "food", "Brunost", "Sweet brown cheese with a caramel taste, eaten in thin slices."],
    ["cheese-slicer", "decor", "budget", "adults", "cooking home-decor", "Cheese slicer", "A Norwegian invention of the 1920s, found in every kitchen."],
    ["troll", "decor", "budget", "kids", "humor collectibles tradition", "Troll figurine", "The long-nosed creature of Norwegian folk tales."],
    ["aquavit", "drink", "mid", "adults", "drinks", "Aquavit", "Caraway-flavoured spirit; one brand matures at sea across the equator."],
    ["viking-ship", "toy", "budget", "kids", "history toys", "Viking ship model", "A model longship from a museum shop."],
  ]),
  country("DK", "Design, cycling, hygge and fairy tales.", "Denmark keeps its own currency, the krone; cards are accepted almost everywhere.", [
    ["lego", "toy", "mid", "kids", "toys games", "LEGO set", "From the country where it was invented; flagship stores sell exclusive sets."],
    ["porcelain", "decor", "premium", "adults", "home-decor collectibles", "Blue fluted porcelain", "Hand-painted blue-and-white tableware made since the 18th century."],
    ["liquorice", "food", "budget", "teens+", "sweets", "Danish liquorice", "From salty classics to chocolate-coated gourmet versions."],
    ["andersen-tales", "book", "budget", "child", "books", "Hans Christian Andersen tales", "An illustrated edition of The Little Mermaid and other stories."],
    ["design-homeware", "decor", "mid", "adults", "home-decor art", "Danish design homeware", "A candlestick, vase or wooden figure by a Danish designer."],
    ["butter-cookies", "food", "budget", "all", "sweets", "Butter cookies", "The classic assortment in a round tin."],
  ]),
  country("FI", "Saunas, lakes, Lapland, design and the Moomins.", "Strong alcohol is sold only in state Alko shops.", [
    ["moomin-mug", "decor", "mid", "all", "collectibles home-decor books", "Moomin mug", "Collectable mugs with Tove Jansson's characters; new designs each year."],
    ["design-textile", "decor", "mid", "adults", "fashion home-decor", "Finnish design textile", "Bold printed fabric, as a bag, apron or tea towel."],
    ["salmiakki", "food", "budget", "teens+", "sweets", "Salmiakki", "Salty liquorice, the national sweet."],
    ["chocolate", "food", "budget", "all", "sweets", "Finnish milk chocolate", "The blue-wrapped bar found in every shop."],
    ["kuksa", "craft", "mid", "adults", "crafts nature tradition", "Kuksa", "A wooden cup carved from birch burl, a Sámi tradition.", { region: "Lapland" }],
    ["sauna-set", "cosmetics", "budget", "adults", "beauty tradition", "Sauna set", "Linen towel, tar soap and a birch-scented oil."],
    ["santa-ornament", "decor", "budget", "child", "tradition toys", "Ornament from Santa's village", "A Christmas decoration from the Arctic Circle in Rovaniemi.", { region: "Lapland", months: [11, 12] }],
  ]),
  country("IS", "Volcanoes, geysers, glaciers and the northern lights.", "Do not take lava, stones or moss from nature; removing them from protected areas is prohibited.", [
    ["lopapeysa", "clothing", "premium", "teens+", "fashion tradition crafts", "Lopapeysa", "The Icelandic wool sweater with a patterned yoke; hand-knitted ones carry a label."],
    ["lava-jewelry", "jewelry", "mid", "adults", "jewelry nature", "Lava jewellery", "Polished black lava set in silver."],
    ["sea-salt", "food", "budget", "adults", "cooking food", "Flaky sea salt", "Produced with geothermal heat in the Westfjords."],
    ["liquorice-chocolate", "food", "budget", "all", "sweets", "Chocolate with liquorice", "The combination Icelanders put in most of their sweets."],
    ["silica-mask", "cosmetics", "mid", "adults", "beauty", "Silica mud mask", "Skincare made with minerals from geothermal lagoons."],
    ["puffin", "toy", "budget", "child", "toys nature", "Plush puffin", "The seabird that nests on Iceland's cliffs each summer."],
  ]),
  country("PL", "Medieval old towns, amber, pierogi and a turbulent history.", "Antiques and older works of art need an export permit.", [
    ["amber", "jewelry", "mid", "adults", "jewelry nature", "Baltic amber jewellery", "Gdańsk is the amber capital; buy from shops that certify it.", { region: "Pomerania" }],
    ["boleslawiec", "decor", "mid", "adults", "home-decor crafts cooking", "Bolesławiec pottery", "Hand-stamped blue stoneware that is safe for the oven.", { region: "Lower Silesia" }],
    ["gingerbread", "food", "budget", "all", "sweets tradition", "Toruń gingerbread", "Spiced pierniki baked in Toruń since the Middle Ages."],
    ["bison-grass-vodka", "drink", "mid", "adults", "drinks", "Bison grass vodka", "Vodka flavoured with a blade of grass from the Białowieża forest."],
    ["krowki", "food", "budget", "all", "sweets", "Krówki", "Soft milk fudge wrapped in paper."],
    ["wycinanki", "craft", "budget", "adults", "crafts art tradition", "Wycinanki", "Colourful paper cut-outs with roosters and flowers."],
    ["glass-baubles", "decor", "mid", "all", "tradition home-decor collectibles", "Hand-blown glass baubles", "Hand-painted Christmas ornaments, a major Polish craft.", { months: [11, 12] }],
  ]),
  country("CZ", "Prague's architecture, beer, crystal and puppetry.", "Many nesting dolls and much 'crystal' in tourist streets are imported; buy glass from named Czech makers.", [
    ["crystal", "decor", "premium", "adults", "home-decor crafts", "Bohemian crystal", "Hand-cut glassware with a centuries-old reputation."],
    ["marionette", "toy", "mid", "kids", "toys crafts tradition", "Wooden marionette", "Hand-carved string puppets, a living Czech tradition."],
    ["becherovka", "drink", "mid", "adults", "drinks", "Becherovka", "Herbal bitter from Karlovy Vary."],
    ["spa-wafers", "food", "budget", "all", "sweets", "Spa wafers", "Large round wafers from the spa towns of West Bohemia."],
    ["garnet", "jewelry", "premium", "adults", "jewelry", "Czech garnet jewellery", "Deep red stones; genuine pieces come with a certificate."],
    ["little-mole", "toy", "budget", "child", "toys books", "Little Mole plush", "Krtek, the cartoon mole every Czech child grows up with."],
    ["beer-cosmetics", "cosmetics", "budget", "adults", "beauty humor", "Beer cosmetics", "Shampoo and soap made with hops and brewer's yeast."],
  ]),
  country("HU", "Thermal baths, paprika, Tokaj wine and Budapest on the Danube.", "Hungary uses the forint, not the euro; exchange booths in tourist streets often give poor rates.", [
    ["paprika", "food", "budget", "adults", "cooking food", "Paprika", "Sweet or hot ground paprika from Szeged or Kalocsa, in a cloth bag or tin."],
    ["tokaji", "drink", "mid", "adults", "drinks", "Tokaji aszú", "Golden sweet wine from the Tokaj hills."],
    ["rubiks-cube", "toy", "budget", "kids", "games toys science", "Rubik's Cube", "Invented in Budapest in 1974 by Ernő Rubik."],
    ["embroidery", "craft", "mid", "adults", "crafts tradition home-decor", "Kalocsa embroidery", "Bright floral needlework on table linen and blouses."],
    ["palinka", "drink", "mid", "adults", "drinks tradition", "Pálinka", "Fruit brandy, most often plum, apricot or pear."],
    ["herend", "decor", "premium", "adults", "home-decor collectibles", "Herend porcelain", "Hand-painted porcelain made since 1826."],
    ["marzipan", "food", "budget", "all", "sweets", "Marzipan figures", "Hungarian confectioners are known for elaborate marzipan."],
  ]),
  country("HR", "The Adriatic coast and islands, Dubrovnik's walls and national parks.", "Croatia uses the euro; on the coast July and August are peak season, with prices to match.", [
    ["licitar", "decor", "budget", "all", "tradition crafts", "Licitar heart", "A red decorated honey-dough heart from Zagreb, given as a token of affection."],
    ["cravat", "accessory", "mid", "adults", "fashion history", "Silk cravat", "The necktie descends from the scarves of 17th-century Croatian soldiers."],
    ["lavender", "cosmetics", "budget", "adults", "beauty nature", "Lavender from Hvar", "Sachets and oil from the island's lavender fields."],
    ["olive-oil", "food", "mid", "adults", "cooking food", "Istrian olive oil", "Peppery oil from the Istrian peninsula.", { region: "Istria" }],
    ["pag-lace", "craft", "premium", "adults", "crafts tradition", "Pag lace", "Needle lace from the island of Pag, on UNESCO's heritage list."],
    ["maraschino", "drink", "mid", "adults", "drinks", "Maraschino", "Cherry liqueur made in Zadar since the 19th century."],
  ]),
  country("RU", "The Hermitage, ballet, literature and the Trans-Siberian railway.", "Icons, antiques and artworks may need an export certificate; check your government's current travel advice.", [
    ["matryoshka", "toy", "mid", "all", "tradition crafts collectibles toys", "Matryoshka", "Nesting wooden dolls, hand-painted."],
    ["khokhloma", "decor", "mid", "adults", "home-decor crafts tradition", "Khokhloma woodware", "Bowls and spoons painted in red, black and gold."],
    ["gzhel", "decor", "mid", "adults", "home-decor crafts", "Gzhel porcelain", "Blue-and-white ceramics from villages near Moscow."],
    ["shawl", "clothing", "mid", "adults", "fashion tradition", "Pavlovo Posad shawl", "A wool shawl printed with large flowers."],
    ["chocolate", "food", "budget", "all", "sweets", "Alyonka chocolate", "The milk chocolate bar with a child's face on the wrapper."],
    ["lacquer-box", "craft", "premium", "adults", "art crafts collectibles", "Lacquer miniature box", "Papier-mâché boxes painted with fairy-tale scenes."],
    ["ushanka", "clothing", "mid", "teens+", "fashion humor", "Ushanka", "The fur-style hat with ear flaps.", { months: [11, 12, 1, 2] }],
  ]),
  country("UA", "Golden-domed churches, embroidered shirts, borscht and the Carpathians.", "Check your government's travel advice before planning a trip.", [
    ["vyshyvanka", "clothing", "premium", "teens+", "fashion tradition crafts", "Vyshyvanka", "The embroidered shirt, with patterns that vary by region."],
    ["pysanka", "craft", "budget", "all", "tradition crafts art", "Pysanka", "An egg decorated with wax-resist patterns, made for Easter.", { months: [3, 4, 5] }],
    ["petrykivka", "decor", "mid", "adults", "art home-decor crafts", "Petrykivka painting", "Woodware and plates with bright floral brushwork."],
    ["kyiv-cake", "food", "budget", "all", "sweets", "Kyiv cake", "A hazelnut meringue cake sold in a round box.", { region: "Kyiv" }],
    ["horilka", "drink", "mid", "adults", "drinks", "Horilka with honey and pepper", "Ukrainian vodka infused with chilli."],
    ["motanka", "toy", "budget", "kids", "toys tradition crafts", "Motanka doll", "A rag doll made without needle or scissors, once a protective charm."],
  ]),
  country("AL", "Riviera beaches, mountain villages, Ottoman-era towns and thousands of concrete bunkers.", "Albania is largely a cash economy and the lek is hard to exchange abroad, so change leftover money before leaving.", [
    ["raki", "drink", "budget", "adults", "drinks", "Raki", "Grape or plum spirit, often home-distilled."],
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Silver filigree", "Fine wire jewellery made by craftsmen in Shkodër and Krujë."],
    ["qeleshe", "clothing", "budget", "adults", "tradition fashion", "Qeleshe", "The traditional white felt cap."],
    ["bunker", "decor", "budget", "teens+", "history humor collectibles", "Miniature bunker", "A stone model of the Cold War bunkers that dot the country."],
    ["mountain-tea", "drink", "budget", "adults", "drinks nature", "Mountain tea", "Dried ironwort (çaj mali) gathered in the highlands.", { soft: true }],
  ]),
  country("AD", "Skiing, hiking and low-tax shopping in the Pyrenees.", "Andorra is outside the EU, so duty-free allowances apply when you cross back into Spain or France.", [
    ["perfume", "cosmetics", "mid", "adults", "beauty", "Perfume", "International brands at low-tax prices."],
    ["mountain-honey", "food", "budget", "all", "food nature", "Mountain honey", "Honey from high Pyrenean meadows."],
    ["cured-sausage", "food", "mid", "adults", "food", "Mountain cured sausage", "Dry sausages such as bringuera; check meat import rules at home."],
    ["outdoor-gear", "clothing", "mid", "teens+", "sports", "Ski or hiking gear", "Outdoor equipment is noticeably cheaper than in neighbouring countries."],
  ]),
  country("BY", "Primeval forest with European bison, linen and Soviet-era architecture.", "Check current entry rules and your government's travel advice before going.", [
    ["linen", "decor", "mid", "adults", "home-decor crafts", "Linen tablecloth", "Belarus is a major flax grower; linen is the classic gift."],
    ["straw-weaving", "craft", "budget", "all", "crafts tradition", "Straw weaving", "Figures and ornaments plaited from rye straw."],
    ["chocolates", "food", "budget", "all", "sweets", "Belarusian chocolates", "Boxed sweets from the Minsk confectionery factories."],
    ["bison-figure", "decor", "budget", "kids", "nature collectibles", "Wooden bison", "A carving of the zubr, the national animal."],
  ]),
  country("BA", "The bridge of Mostar, Sarajevo's bazaar and Bosnian coffee.", "The convertible mark cannot be exchanged abroad; change leftover cash before leaving.", [
    ["coffee-set", "decor", "mid", "adults", "drinks crafts tradition", "Copper coffee set", "A hand-hammered džezva with small cups, from Sarajevo's coppersmiths."],
    ["kilim", "decor", "premium", "adults", "home-decor crafts", "Bosnian kilim", "A flat-woven wool rug with geometric patterns."],
    ["rahat-lokum", "food", "budget", "all", "sweets", "Rahat lokum", "Soft sweets served alongside coffee."],
    ["copper-plate", "craft", "mid", "adults", "crafts art", "Engraved copper plate", "Decorative plates engraved with city scenes."],
  ]),
  country("BG", "Rose oil, Black Sea resorts, yogurt and Orthodox monasteries.", "The Rose Valley harvest and festival take place in late May and early June.", [
    ["rose-oil", "cosmetics", "mid", "adults", "beauty tradition", "Rose oil and rose water", "Bulgaria is one of the world's main producers of rose oil."],
    ["martenitsa", "jewelry", "budget", "all", "tradition crafts", "Martenitsa", "Red-and-white threads worn from 1 March until the first stork is seen.", { months: [2, 3] }],
    ["troyan-pottery", "decor", "mid", "adults", "home-decor crafts", "Troyan pottery", "Glazed ceramics with a drip pattern."],
    ["rakia", "drink", "mid", "adults", "drinks", "Rakia", "Fruit brandy, usually grape or plum."],
    ["sharena-sol", "food", "budget", "adults", "cooking food", "Sharena sol", "'Colourful salt', a layered spice mix eaten with bread."],
  ]),
  country("CY", "Beaches, ancient ruins, halloumi and the legendary birthplace of Aphrodite.", "The island is divided; quantity limits apply to goods carried from the north to the south.", [
    ["lefkara-lace", "craft", "premium", "adults", "crafts tradition home-decor", "Lefkara lace", "Embroidered linen from the village of Lefkara."],
    ["commandaria", "drink", "mid", "adults", "drinks history", "Commandaria", "A sweet wine with a name in use since the Crusades."],
    ["halloumi", "food", "budget", "adults", "food", "Halloumi", "Vacuum-packed grilling cheese; check dairy import rules outside the EU."],
    ["loukoumi", "food", "budget", "all", "sweets", "Loukoumi", "Cyprus delight flavoured with rose or bergamot."],
    ["carob-syrup", "food", "budget", "adults", "cooking food", "Carob syrup", "A dark sweet syrup once called 'black gold'."],
  ]),
  country("EE", "Tallinn's medieval old town, forests, saunas and digital government.", "Much amber sold in the Baltics is imitation; buy from shops that certify it.", [
    ["mittens", "clothing", "mid", "adults", "fashion crafts tradition", "Patterned wool mittens", "Hand-knitted with traditional regional patterns."],
    ["juniper-wood", "decor", "budget", "adults", "cooking crafts home-decor", "Juniper kitchenware", "Butter knives and trivets that keep their scent for years."],
    ["vana-tallinn", "drink", "mid", "adults", "drinks", "Vana Tallinn", "A rum-based liqueur with citrus and spices."],
    ["chocolate", "food", "budget", "all", "sweets", "Estonian chocolate", "From the country's oldest confectionery maker."],
    ["marzipan", "food", "budget", "all", "sweets art", "Hand-painted marzipan", "Tallinn claims marzipan as its own medieval invention.", { region: "Tallinn" }],
  ]),
  country("LV", "Art Nouveau Riga, pine-backed beaches and song festivals.", "Riga Black Balsam is 45% alcohol: airline liquid limits apply in hand luggage.", [
    ["black-balsam", "drink", "mid", "adults", "drinks tradition", "Riga Black Balsam", "A bitter herbal liqueur in a ceramic bottle."],
    ["amber", "jewelry", "mid", "adults", "jewelry nature", "Baltic amber", "Jewellery of fossil resin washed up on the Baltic shore."],
    ["linen", "decor", "mid", "adults", "home-decor crafts", "Linen textiles", "Towels and table runners in natural flax."],
    ["chocolate", "food", "budget", "all", "sweets", "Latvian chocolate", "Boxed sweets from Riga's historic chocolate maker."],
    ["mittens", "clothing", "mid", "adults", "crafts tradition fashion", "Latvian mittens", "Knitted in patterns that differ from region to region."],
  ]),
  country("LT", "Baltic amber, baroque Vilnius, the dunes of the Curonian Spit and basketball.", "Real amber feels warm and floats in salt water; buy from shops that certify it.", [
    ["amber", "jewelry", "mid", "adults", "jewelry nature", "Baltic amber", "Lithuania's 'gold', sold everywhere along the coast."],
    ["linen", "decor", "mid", "adults", "home-decor crafts", "Linen", "Table linen and clothing woven from local flax."],
    ["sakotis", "food", "mid", "all", "sweets tradition", "Šakotis", "A spiky 'tree cake' baked on a rotating spit."],
    ["mead", "drink", "mid", "adults", "drinks tradition", "Midus", "Lithuanian mead made from honey and herbs."],
    ["basketball-jersey", "clothing", "mid", "teens+", "sports", "Basketball jersey", "Basketball is close to a national religion."],
  ]),
  country("LI", "A tiny Alpine principality with a castle, banks and collectable stamps.", "The tourist office in Vaduz adds a souvenir stamp to your passport for a small fee.", [
    ["stamps", "art", "budget", "adults", "collectibles history", "Postage stamps", "Liechtenstein's stamps are prized by collectors worldwide."],
    ["wine", "drink", "mid", "adults", "drinks", "Wine from the Prince's winery", "Pinot noir grown below the castle in Vaduz."],
    ["chocolates", "food", "budget", "all", "sweets", "Crown chocolates", "Pralines shaped like the princely crown."],
    ["ceramics", "decor", "mid", "adults", "home-decor crafts", "Hand-painted ceramics", "Tableware from the country's long-standing pottery."],
  ]),
  country("LU", "A fortified old town, banks, castles and three official languages.", "All public transport in the country is free.", [
    ["tableware", "decor", "premium", "adults", "home-decor collectibles", "Porcelain tableware", "From a maker rooted in Luxembourg since the 18th century."],
    ["cremant", "drink", "mid", "adults", "drinks", "Crémant de Luxembourg", "Sparkling wine from the Moselle valley."],
    ["peckvillchen", "craft", "budget", "all", "tradition crafts music", "Péckvillchen", "A clay bird whistle sold at the Easter Monday pottery fair.", { months: [3, 4] }],
    ["mustard", "food", "budget", "adults", "cooking food", "Luxembourg mustard", "The local mustard found on every table."],
  ]),
  country("MT", "Fortified harbours, honey-coloured stone, prehistoric temples and clear diving waters.", "Malta drives on the left and uses British three-pin plugs.", [
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Silver filigree", "Often shaped as the eight-pointed Maltese cross."],
    ["mdina-glass", "decor", "mid", "adults", "home-decor art crafts", "Mdina glass", "Hand-blown glass in sea blues and greens."],
    ["gozo-lace", "craft", "premium", "adults", "crafts tradition", "Gozo lace", "Bobbin lace made on the island of Gozo.", { region: "Gozo" }],
    ["honey", "food", "budget", "all", "food nature", "Maltese honey", "Thyme honey; the island's ancient name is linked to honey."],
    ["bajtra", "drink", "mid", "adults", "drinks", "Bajtra", "Liqueur made from prickly pears."],
  ]),
  country("MD", "Wine cellars that run for kilometres, monasteries and rural traditions.", "Transnistria is a breakaway region with its own border checks and currency.", [
    ["wine", "drink", "mid", "adults", "drinks", "Moldovan wine", "From underground cellars that are among the largest in the world."],
    ["divin", "drink", "mid", "adults", "drinks", "Divin", "Moldovan aged brandy."],
    ["carpet", "decor", "premium", "adults", "home-decor crafts tradition", "Hand-woven carpet", "Wool carpets with floral motifs on a dark ground."],
    ["martisor", "jewelry", "budget", "all", "tradition crafts", "Mărțișor", "A red-and-white charm given on 1 March.", { months: [2, 3] }],
    ["embroidered-towel", "craft", "mid", "adults", "crafts tradition home-decor", "Embroidered towel", "A ceremonial prosop with woven and stitched patterns."],
  ]),
  country("MC", "The Monte Carlo casino, the Grand Prix and superyachts.", "Monaco uses the euro and has no border checks with France.", [
    ["grand-prix", "clothing", "mid", "teens+", "sports collectibles", "Grand Prix merchandise", "Caps and shirts from the famous street race."],
    ["playing-cards", "accessory", "budget", "adults", "games collectibles", "Casino playing cards", "A deck from the Monte Carlo casino shop."],
    ["stamps", "art", "budget", "adults", "collectibles", "Monaco stamps", "Finely engraved issues sought by collectors."],
    ["chocolates", "food", "mid", "all", "sweets", "Monaco chocolates", "From the principality's own chocolate house."],
  ]),
  country("ME", "The Bay of Kotor, Adriatic beaches and rugged mountains.", "Montenegro uses the euro although it is not in the EU.", [
    ["prsut", "food", "mid", "adults", "food", "Njeguši pršut", "Smoked dry-cured ham; check meat import rules at home."],
    ["vranac", "drink", "mid", "adults", "drinks", "Vranac wine", "A dark red from the local grape."],
    ["olive-oil", "food", "mid", "adults", "cooking food", "Olive oil from Bar", "The coast has olive trees said to be two thousand years old."],
    ["cap", "clothing", "budget", "adults", "tradition fashion", "Montenegrin cap", "A flat round cap with a red top and gold embroidery."],
    ["honey", "food", "budget", "all", "food nature", "Mountain honey", "From meadows in the northern highlands."],
  ]),
  country("MK", "Lake Ohrid, Byzantine churches and Ottoman bazaars.", "The denar is hard to exchange abroad; change leftover cash before leaving.", [
    ["ohrid-pearls", "jewelry", "mid", "adults", "jewelry crafts", "Ohrid pearls", "Made to a family recipe from shell and the scales of a lake fish.", { region: "Ohrid" }],
    ["ajvar", "food", "budget", "adults", "food cooking", "Ajvar", "Roasted red pepper spread, made each autumn."],
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Silver filigree", "Fine wirework from the old bazaar workshops."],
    ["wine", "drink", "mid", "adults", "drinks", "Tikveš wine", "Red wine from the country's main wine region."],
  ]),
  country("SM", "A mountaintop republic with medieval towers, among the oldest states in the world.", "The tourist office stamps passports as a souvenir for a small fee.", [
    ["stamps-coins", "art", "budget", "adults", "collectibles", "Stamps and euro coins", "San Marino issues its own, popular with collectors."],
    ["ceramics", "decor", "mid", "adults", "home-decor crafts", "Ceramics", "Hand-painted pottery sold in the old town."],
    ["torta-tre-monti", "food", "budget", "all", "sweets", "Torta Tre Monti", "A layered wafer and hazelnut cake named after the three towers."],
    ["three-towers", "decor", "budget", "all", "collectibles", "Three Towers miniature", "A model of the fortresses on Monte Titano."],
  ]),
  country("RS", "Belgrade's nightlife, monasteries, brass bands and rakija.", "The dinar is hard to exchange abroad; change leftover cash before leaving.", [
    ["sljivovica", "drink", "mid", "adults", "drinks tradition", "Šljivovica", "Plum rakija, the national drink."],
    ["ajvar", "food", "budget", "adults", "food cooking", "Ajvar", "Roasted pepper relish, best from Leskovac."],
    ["opanci", "clothing", "mid", "adults", "tradition crafts", "Opanci", "Leather peasant shoes with a curled toe."],
    ["pirot-kilim", "decor", "premium", "adults", "home-decor crafts tradition", "Pirot kilim", "A flat-woven rug identical on both sides."],
    ["tesla", "book", "budget", "teens+", "science history", "Nikola Tesla memorabilia", "Books and models from the Tesla Museum in Belgrade."],
  ]),
  country("SK", "Castles, the High Tatras and folk traditions.", "Many castles and mountain huts close or shorten their hours in winter.", [
    ["majolica", "decor", "mid", "adults", "home-decor crafts tradition", "Modra majolica", "Hand-painted pottery from the town of Modra."],
    ["corn-husk-doll", "toy", "budget", "kids", "toys crafts tradition", "Corn-husk doll", "Figures of village life made from dried maize leaves."],
    ["tea-liqueur", "drink", "mid", "adults", "drinks", "Tatra tea liqueur", "A strong tea-based liqueur from the mountains."],
    ["fujara", "music", "premium", "adults", "music tradition crafts", "Fujara", "The long shepherd's flute, on UNESCO's heritage list."],
    ["mead", "drink", "budget", "adults", "drinks", "Medovina", "Slovak honey wine."],
  ]),
  country("SI", "Lake Bled, caves, Alpine peaks and beekeeping.", "Distances are short: the coast, the caves and the Alps fit into a single trip.", [
    ["honey", "food", "budget", "all", "food nature", "Slovenian honey", "From a country with one of the highest numbers of beekeepers per person."],
    ["beehive-panel", "art", "mid", "adults", "art tradition home-decor", "Painted beehive panel", "Folk scenes once painted on the fronts of hives."],
    ["idrija-lace", "craft", "premium", "adults", "crafts tradition", "Idrija lace", "Bobbin lace from the old mining town."],
    ["piran-salt", "food", "budget", "adults", "cooking food", "Piran sea salt", "Hand-harvested in salt pans worked since the Middle Ages."],
  ]),
  country("VA", "St Peter's Basilica, the Sistine Chapel and the Vatican Museums.", "Shoulders and knees must be covered to enter the basilica and the museums.", [
    ["rosary", "jewelry", "budget", "adults", "tradition jewelry", "Rosary", "Sold around St Peter's; it can be blessed at a papal audience."],
    ["stamps-coins", "art", "budget", "adults", "collectibles history", "Vatican stamps and coins", "Issued in small numbers and collected worldwide."],
    ["museum-print", "art", "budget", "adults", "art history", "Museum art print", "A Raphael or Michelangelo reproduction from the museum shop."],
    ["swiss-guard", "toy", "budget", "kids", "toys collectibles history", "Swiss Guard figurine", "A model of the guards in their striped uniform."],
  ]),
  country("XK", "Ottoman-era Prizren, mountain hiking and a young café culture.", "Kosovo uses the euro; check entry rules if you plan to continue directly into Serbia.", [
    ["filigree", "jewelry", "mid", "adults", "jewelry crafts", "Prizren filigree", "Silver wirework from one of the Balkans' filigree centres.", { region: "Prizren" }],
    ["plis", "clothing", "budget", "adults", "tradition fashion", "Plis", "The white felt cap of Albanian tradition."],
    ["mountain-honey", "food", "budget", "all", "food nature", "Mountain honey", "From the Rugova and Sharr highlands."],
    ["rakia", "drink", "budget", "adults", "drinks", "Rakia", "Grape or plum brandy."],
  ]),
];
