import { country, type CountrySeed } from "../define";

/** The twelve countries the catalogue started with. */
export const featured: CountrySeed[] = [
  country("AU", "Beaches, the Outback, the Great Barrier Reef and wildlife found nowhere else.", "Biosecurity rules are among the strictest in the world: declare all food, plant and wooden items on arrival.", [
    ["boomerang", "craft", "mid", "all", "tradition sports art", "Hand-painted boomerang", "A wooden boomerang decorated by Aboriginal artists; look for one sold with the artist's name."],
    ["plush-koala", "toy", "budget", "child", "toys nature", "Plush koala", "A soft koala toy, the classic gift for small children."],
    ["tim-tam", "food", "budget", "all", "sweets food", "Tim Tam biscuits", "Chocolate-coated biscuits found in every supermarket, easy to share at school or work."],
    ["vegemite", "food", "budget", "teens+", "food humor", "Jar of Vegemite", "The salty yeast spread Australians grow up on; a fun dare for friends."],
    ["opal-pendant", "jewelry", "premium", "adults", "jewelry fashion", "Opal pendant", "Australia produces most of the world's opal; a small pendant is a lasting gift."],
    ["akubra-hat", "clothing", "premium", "adults", "fashion nature", "Akubra hat", "The wide-brimmed felt bush hat, made in Australia since the 19th century."],
    ["macadamia", "food", "mid", "all", "food sweets", "Chocolate macadamia nuts", "Macadamias are native to Queensland; the chocolate-covered ones travel well.", { region: "Queensland" }],
    ["aboriginal-art-print", "art", "mid", "adults", "art tradition home-decor", "Aboriginal dot-painting print", "A print from a community art centre, which ensures the artist is paid fairly."],
  ]),
  country("RO", "Transylvanian castles, painted monasteries, the Carpathians and the Danube Delta.", "On 1 March people give each other mărțișor charms; stalls sell them from mid-February.", [
    ["martisor", "jewelry", "budget", "all", "tradition jewelry crafts", "Mărțișor", "A small charm on a red-and-white string, given on 1 March to welcome spring.", { months: [2, 3] }],
    ["ie-blouse", "clothing", "premium", "teens+", "fashion tradition crafts", "Ie (embroidered blouse)", "The traditional hand-embroidered blouse; patterns differ from region to region."],
    ["horezu-ceramics", "decor", "mid", "adults", "home-decor crafts tradition", "Horezu ceramic plate", "Pottery with the rooster motif, a craft on UNESCO's intangible heritage list.", { region: "Vâlcea" }],
    ["painted-eggs", "craft", "mid", "adults", "tradition crafts collectibles", "Painted Easter eggs", "Eggs decorated with fine wax-resist patterns, a speciality of Bucovina.", { region: "Bucovina", months: [3, 4, 5] }],
    ["zacusca", "food", "budget", "all", "food cooking", "Jar of zacuscă", "A roasted aubergine and pepper spread, made in autumn and eaten on bread.", { months: [9, 10, 11] }],
    ["tuica", "drink", "mid", "adults", "drinks tradition", "Țuică (plum brandy)", "The national spirit, distilled from plums and offered to guests before a meal."],
    ["dracula-mug", "decor", "budget", "teens-adults", "humor collectibles books", "Dracula mug", "A tongue-in-cheek souvenir from the castles of Transylvania.", { region: "Transylvania" }],
    ["rom-chocolate", "food", "budget", "all", "sweets food", "ROM chocolate bar", "A rum-flavoured chocolate bar in a wrapper showing the Romanian flag."],
  ]),
  country("FR", "Food and wine, fashion, art museums and the Eiffel Tower.", "Residents of non-EU countries can claim a VAT refund (détaxe) on larger purchases made in one shop on the same day.", [
    ["eiffel-porcelain", "decor", "mid", "adults", "home-decor collectibles", "Porcelain Eiffel Tower figurine", "A delicate ornament of the tower, well suited to a display cabinet.", { region: "Paris" }],
    ["science-kit", "toy", "mid", "kids", "science tech toys", "Science experiment kit", "A hands-on kit from the shop of a science museum such as the Palais de la Découverte.", { region: "Paris" }],
    ["macarons", "food", "mid", "all", "sweets food", "Box of macarons", "Almond meringue biscuits in many flavours; buy them on the last day, they keep under a week."],
    ["provence-lavender", "cosmetics", "budget", "adults", "beauty nature home-decor", "Lavender sachets", "Dried lavender from the fields of Provence, harvested in summer.", { region: "Provence", months: [6, 7, 8] }],
    ["marseille-soap", "cosmetics", "budget", "teens+", "beauty tradition", "Savon de Marseille", "The traditional olive-oil soap cube, stamped with its oil content.", { region: "Provence" }],
    ["breton-shirt", "clothing", "mid", "all", "fashion", "Breton striped shirt", "The navy-and-white marinière, originally the French sailor's uniform.", { region: "Brittany" }],
    ["champagne", "drink", "premium", "adults", "drinks", "Bottle of champagne", "Bought from a small grower, it costs less and has a story to tell.", { region: "Champagne" }],
    ["petit-prince", "book", "budget", "all", "books art", "Le Petit Prince", "An illustrated edition of Saint-Exupéry's tale, in French or in the recipient's language."],
  ]),
  country("IT", "Art cities, Roman ruins, regional cooking and design.", "Buying counterfeit designer goods from street sellers is illegal, and the buyer can be fined too.", [
    ["murano-glass", "decor", "premium", "adults", "home-decor art crafts", "Murano glass ornament", "Hand-blown glass from the island of Murano; check for the Vetro Artistico mark.", { region: "Veneto" }],
    ["venetian-mask", "craft", "mid", "teens+", "art tradition collectibles", "Venetian carnival mask", "A papier-mâché mask, most fitting around the Carnival in late winter.", { region: "Veneto", months: [1, 2] }],
    ["limoncello", "drink", "mid", "adults", "drinks food", "Limoncello", "Lemon liqueur from the Amalfi Coast and Sorrento, served ice cold.", { region: "Campania" }],
    ["moka-pot", "decor", "mid", "adults", "cooking drinks home-decor", "Moka pot", "The stovetop coffee maker found in nearly every Italian kitchen."],
    ["pinocchio", "toy", "budget", "child", "toys books crafts", "Wooden Pinocchio", "A painted wooden puppet of the character created by the Tuscan writer Collodi.", { region: "Tuscany" }],
    ["leather-wallet", "accessory", "premium", "adults", "fashion crafts", "Florentine leather wallet", "Florence is known for its leather workshops; small goods are the easiest to bring home.", { region: "Tuscany" }],
    ["balsamic-vinegar", "food", "mid", "adults", "cooking food", "Balsamic vinegar of Modena", "Aged grape-must vinegar; a small bottle goes a long way.", { region: "Emilia-Romagna" }],
    ["torrone", "food", "budget", "all", "sweets tradition", "Torrone", "Honey and almond nougat, the traditional Christmas sweet.", { months: [11, 12] }],
  ]),
  country("ES", "Beaches, late dinners, flamenco, football and Gaudí's architecture.", "Jamón and other meat products cannot be taken into many countries outside the EU.", [
    ["hand-fan", "accessory", "budget", "teens+", "fashion tradition crafts", "Hand fan (abanico)", "A painted folding fan, practical in the southern summer heat.", { region: "Andalusia" }],
    ["turron", "food", "budget", "all", "sweets tradition", "Turrón", "Almond nougat from Alicante and Jijona, eaten at Christmas.", { months: [11, 12] }],
    ["olive-oil", "food", "mid", "adults", "cooking food", "Extra virgin olive oil", "Spain is the world's largest producer; a tin is safer in luggage than glass.", { region: "Andalusia" }],
    ["espadrilles", "clothing", "mid", "teens+", "fashion", "Espadrilles", "Canvas shoes with a rope sole, worn all summer."],
    ["football-scarf", "clothing", "budget", "all", "sports collectibles", "Football club scarf", "A scarf from the local club, for the fan in the family."],
    ["saffron", "food", "mid", "adults", "cooking food", "La Mancha saffron", "Protected-origin saffron, light to carry and essential for paella.", { region: "Castilla-La Mancha" }],
    ["gaudi-mosaic", "decor", "budget", "all", "art home-decor collectibles", "Gaudí-style mosaic lizard", "A small tiled figure inspired by the Park Güell salamander in Barcelona.", { region: "Catalonia" }],
    ["castanets", "music", "budget", "kids", "music tradition toys", "Castanets", "The hand percussion of flamenco, fun for children to try.", { region: "Andalusia" }],
  ]),
  country("DE", "Christmas markets, beer, castles, cars and engineering.", "Most shops are closed on Sundays; Christmas markets run from late November until just before Christmas.", [
    ["beer-stein", "decor", "mid", "adults", "drinks collectibles tradition", "Beer stein", "A stoneware mug with a pewter lid, the Bavarian classic.", { region: "Bavaria" }],
    ["cuckoo-clock", "decor", "premium", "adults", "home-decor crafts tradition", "Black Forest cuckoo clock", "A carved wooden clock; genuine ones carry a Black Forest certificate.", { region: "Baden-Württemberg" }],
    ["nutcracker", "craft", "mid", "all", "tradition crafts collectibles", "Wooden nutcracker", "A painted soldier figure from the Ore Mountains, sold at Christmas markets.", { region: "Saxony", months: [11, 12] }],
    ["lebkuchen", "food", "budget", "all", "sweets tradition", "Nuremberg Lebkuchen", "Soft spiced gingerbread, often sold in a decorated tin.", { region: "Bavaria", months: [11, 12] }],
    ["haribo", "food", "budget", "kids", "sweets", "Haribo gummy bears", "The original gummy bears, with flavours not sold abroad."],
    ["ampelmann", "accessory", "budget", "all", "humor history collectibles", "Ampelmann keyring", "The little man from East Berlin's pedestrian lights, now a city mascot.", { region: "Berlin" }],
    ["steiff-bear", "toy", "premium", "child", "toys collectibles", "Steiff teddy bear", "From the company that made the first teddy bears, each with a button in its ear."],
    ["riesling", "drink", "mid", "adults", "drinks", "Riesling wine", "A white wine from the Mosel or Rhine valleys.", { region: "Rhineland-Palatinate" }],
  ]),
  country("PT", "Azulejo tiles, port wine, fado, surfing and custard tarts.", "Avoid antique azulejos at flea markets: many have been stolen from building façades.", [
    ["azulejo-tile", "decor", "budget", "adults", "home-decor art tradition", "Azulejo tile", "A painted ceramic tile; buy new ones, as antique tiles are often stolen from buildings."],
    ["cork-wallet", "accessory", "mid", "teens+", "fashion nature", "Cork wallet", "Portugal is the world's largest cork producer; the material is light and water-resistant."],
    ["port-wine", "drink", "mid", "adults", "drinks tradition", "Port wine", "Fortified wine from the Douro valley, aged in the cellars across the river from Porto.", { region: "Porto" }],
    ["barcelos-rooster", "decor", "budget", "all", "tradition collectibles home-decor", "Rooster of Barcelos", "The colourful ceramic rooster, a national symbol of good luck."],
    ["tinned-sardines", "food", "budget", "adults", "food collectibles", "Tinned sardines", "Sold in retro illustrated tins that are as much a gift as the fish."],
    ["ginjinha", "drink", "budget", "adults", "drinks sweets", "Ginjinha", "Sour cherry liqueur, sometimes sold with small chocolate cups.", { region: "Lisbon" }],
    ["embroidered-linen", "decor", "premium", "adults", "home-decor crafts tradition", "Madeira embroidery", "Hand-embroidered table linen, certified with a lead or holographic seal.", { region: "Madeira" }],
    ["fado-cd", "music", "budget", "adults", "music tradition", "Fado recording", "A record of the melancholic Lisbon song tradition, for music lovers.", { region: "Lisbon" }],
  ]),
  country("TR", "Bazaars, Istanbul's mosques, Cappadocia and Mediterranean beaches.", "Taking antiques, old carpets, old coins or even stones from ancient sites out of the country without a permit is a crime.", [
    ["turkish-delight", "food", "budget", "all", "sweets food tradition", "Turkish delight (lokum)", "Soft sweets with rose, pistachio or pomegranate, sold by weight."],
    ["nazar", "decor", "budget", "all", "tradition home-decor jewelry", "Nazar (evil eye bead)", "The blue glass charm hung in homes and cars to ward off bad luck."],
    ["tea-glasses", "decor", "budget", "adults", "drinks home-decor tradition", "Tulip tea glasses", "A set of the small curved glasses in which Turkish tea is served."],
    ["coffee-cezve", "decor", "mid", "adults", "drinks cooking crafts", "Copper cezve and coffee", "The long-handled pot for brewing Turkish coffee, paired with finely ground beans."],
    ["iznik-ceramics", "decor", "mid", "adults", "home-decor art crafts", "İznik-style ceramic bowl", "Hand-painted pottery with tulip and carnation motifs."],
    ["peshtemal", "clothing", "mid", "teens+", "fashion beauty", "Peştemal towel", "The thin woven cotton towel of the hammam, also used as a beach wrap."],
    ["baklava", "food", "mid", "all", "sweets food", "Pistachio baklava", "Gaziantep is its home; shops will pack a box for travel.", { region: "Gaziantep" }],
    ["mosaic-lamp", "decor", "mid", "teens+", "home-decor crafts", "Mosaic glass lamp", "A lamp of coloured glass pieces, a favourite from the Grand Bazaar."],
  ]),
  country("GR", "Ancient sites, islands, olive oil and the birthplace of democracy.", "Exporting antiquities is a serious crime; buy only certified museum replicas.", [
    ["olive-oil-soap", "cosmetics", "budget", "teens+", "beauty nature", "Olive oil soap", "Simple, gentle soap made from local olive oil."],
    ["komboloi", "accessory", "budget", "adults", "tradition collectibles", "Komboloi (worry beads)", "A string of beads flipped through the fingers to pass the time."],
    ["thyme-honey", "food", "mid", "all", "food sweets nature", "Thyme honey", "Aromatic honey from the islands, especially Crete."],
    ["ouzo", "drink", "mid", "adults", "drinks tradition", "Ouzo", "The anise-flavoured spirit that turns cloudy with water."],
    ["leather-sandals", "clothing", "mid", "teens+", "fashion crafts", "Handmade leather sandals", "Made to measure in small workshops in Athens and on the islands."],
    ["mythology-book", "book", "budget", "kids", "books history", "Illustrated Greek myths", "A children's retelling of the myths, sold at museum shops."],
    ["mastiha", "food", "mid", "adults", "food sweets tradition", "Chios mastiha", "A resin harvested only on Chios, sold as sweets, gum or liqueur.", { region: "Chios" }],
    ["museum-replica", "art", "mid", "adults", "history art collectibles", "Museum replica vase", "A certified copy of an ancient vase from an archaeological museum shop."],
  ]),
  country("GB", "Royal pageantry, pubs, museums, football and green countryside.", "The UK is outside the EU, so customs allowances apply on the way home; the big national museums are free.", [
    ["english-tea", "drink", "budget", "adults", "drinks tradition", "English breakfast tea", "A tin of loose-leaf tea from a traditional tea merchant.", { soft: true }],
    ["shortbread", "food", "budget", "all", "sweets food", "Scottish shortbread", "Buttery biscuits in a tartan tin, easy to share.", { region: "Scotland" }],
    ["tartan-scarf", "clothing", "mid", "teens+", "fashion tradition", "Tartan lambswool scarf", "A warm scarf in a clan tartan, most welcome in the cold months.", { region: "Scotland", months: [10, 11, 12, 1, 2] }],
    ["paddington", "toy", "mid", "child", "toys books", "Paddington Bear", "The bear in the blue duffle coat from the children's books.", { region: "London" }],
    ["whisky", "drink", "premium", "adults", "drinks collectibles", "Single malt Scotch whisky", "A bottle from a distillery you visited makes it personal.", { region: "Scotland" }],
    ["double-decker", "toy", "budget", "child", "toys collectibles", "Red double-decker bus model", "A die-cast model of the London bus.", { region: "London" }],
    ["penguin-classic", "book", "budget", "teens+", "books", "Clothbound classic novel", "A handsome edition of Austen or Dickens from a British bookshop."],
    ["museum-dinosaur-kit", "toy", "mid", "kids", "science nature toys", "Dinosaur excavation kit", "A dig-it-yourself fossil kit from a natural history museum shop.", { region: "London" }],
  ]),
  country("JP", "Temples, cherry blossom, cuisine, anime and bullet trains.", "Visitors can shop tax-free on showing a passport; every station sells boxed regional sweets (omiyage) meant as gifts.", [
    ["matcha-kitkat", "food", "budget", "all", "sweets food humor", "Matcha KitKat", "One of the many Japan-only flavours, individually wrapped for sharing."],
    ["furoshiki", "accessory", "budget", "adults", "crafts tradition fashion", "Furoshiki wrapping cloth", "A patterned square cloth used to wrap gifts or carry things."],
    ["daruma", "decor", "budget", "all", "tradition collectibles home-decor", "Daruma doll", "Paint one eye when setting a goal and the other when you reach it; popular at New Year.", { months: [12, 1] }],
    ["chopsticks", "decor", "mid", "teens+", "cooking crafts home-decor", "Lacquered chopsticks", "A pair in a gift box; some shops engrave a name while you wait."],
    ["sake", "drink", "mid", "adults", "drinks tradition", "Sake", "Rice wine from a regional brewery, often sold in small gift bottles."],
    ["gachapon", "toy", "budget", "kids", "toys collectibles games", "Gachapon capsule toys", "Small collectable figures from the capsule machines found everywhere."],
    ["stationery", "accessory", "budget", "teens-adults", "art crafts tech", "Japanese stationery set", "Fine-tipped pens, washi tape and notebooks from a stationery store."],
    ["kitchen-knife", "decor", "premium", "adults", "cooking crafts", "Japanese kitchen knife", "A hand-forged santoku; pack it in checked luggage."],
  ]),
  country("BR", "Carnival, football, the Amazon, beaches and coffee.", "Products made from wild animals, feathers or coral are illegal to buy or export.", [
    ["havaianas", "clothing", "budget", "all", "fashion sports", "Havaianas flip-flops", "The Brazilian rubber sandals, far cheaper at home than abroad."],
    ["coffee", "drink", "mid", "adults", "drinks cooking", "Speciality coffee beans", "Single-origin beans from the world's largest coffee producer.", { region: "Minas Gerais", soft: true }],
    ["cachaca", "drink", "mid", "adults", "drinks tradition", "Cachaça", "The sugarcane spirit at the heart of the caipirinha."],
    ["football-shirt", "clothing", "mid", "all", "sports fashion", "Brazil football shirt", "The yellow national team jersey."],
    ["brigadeiro", "food", "budget", "all", "sweets food", "Brigadeiros", "Chocolate fudge truffles rolled in sprinkles, a staple of every birthday party."],
    ["senhor-do-bonfim-ribbon", "accessory", "budget", "all", "tradition jewelry", "Bonfim wish ribbon", "A coloured ribbon from Salvador tied with three knots, one wish each.", { region: "Bahia" }],
    ["pandeiro", "music", "mid", "teens+", "music tradition", "Pandeiro", "The hand frame drum of samba, compact enough for a suitcase."],
    ["gemstones", "jewelry", "premium", "adults", "jewelry nature collectibles", "Brazilian gemstone jewellery", "Amethyst, tourmaline or topaz pieces from a certified jeweller.", { region: "Minas Gerais" }],
    ["artist-shirt", "clothing", "budget", "teens+", "music fashion", "Brazilian music T-shirt", "A shirt or record by a local artist, from samba and bossa nova greats to today's sertanejo and funk stars."],
  ]),
];
